### ISSUE TITLE
Delay when writing /lock

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1829] opened 2019-07-15 21:21 UTC
You can not spam /lock anymore (for example press lock key twice to check if your team is locked), there is a weird delay inbetween. Definnitely wasnt like that before

**Comment by heinrich5991** [comment] 2019-07-15 21:27
#1122

**Comment by Learath2** [comment] 2019-07-15 22:03
Might be a good idea to add an indicator for this, maybe in part of the team display I was thinking of.

**Comment by fokkonaut** [comment] 2019-07-16 10:42
It wasnt like this like 3 days ago :D

**Comment by fokkonaut** [comment] 2019-07-17 09:39
I think the delay should be removed, its really weird and if someone wants to spam they can do it in another way too. Also you can simply change team, lock, and invite your other friends.

**Comment by heinrich5991** [comment] 2019-07-17 09:52
What other ways exist for spamming? They should preferably be fixed as well.

**Comment by fokkonaut** [comment] 2019-07-17 20:06
You can always spam? Just write a chat message every 4-5 seconds

**Comment by Learath2** [comment] 2019-07-17 20:43
The delay applied here is the exact same delay applied to chat messages iirc, so you can't spam with ridiculous speed.

**Comment by fokkonaut** [comment] 2019-07-18 01:49
Chat commands dont have a delay, except this one

**Comment by Learath2** [comment] 2019-07-18 05:38
Chat commands that generate output to everyone should

**Comment by Learath2** [comment] 2019-07-18 15:22
Wontfix, working as intended.

**Closed by Learath2** 2019-07-18 15:22 UTC
Labels: server
