### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#994] opened 2018-01-16 21:57 UTC
even with fsaa samples 0 i see some borders at the of end some tiles.

**Comment by Jupeyy** [comment] 2018-01-17 07:57
1. Pics
2. Map
3. You didn't get what exactly was changed, before all tiles were sent every frame, that's why the texture offset could be adjusted always. Now it's buffered... Means i never want to touch/change the tiles again(until a new map is loaded), which reduces the CPU overhead extremly, and theoretically also makes rendering faster, because the GPU can load the stuff from it's cache or VRAM which is much faster than sending it from the CPU.

I force nobody to use the new opengl version, it's fully experimental. Currently we also have a small performance issue with older GPUs, which hopefully will be fixed until next month.

**Comment by def-** [comment] 2018-01-17 07:59
> small performance issue

10 fps instead of 80 fps is not so small for me.

**Comment by Jupeyy** [comment] 2018-01-17 08:02
As I said a few billion times now, it's not really related to my code itself, but because of the strange stream buffer behaviour. 80FPS from any GPU on the world is just redicilous, my brothers 12 years old laptop gets 800 frames.
On a realistic GPU the performance is not so bad that you can't play, but it drops alot of frames in specific scenarios.

**Comment by heinrich5991** [comment] 2018-02-01 12:19
Dunno if related or not, but the map "Piranha" looks really weird when moving around. When standing still, it's okay, but moving around makes the whole map wiggle. Reported by @fokkonaut.

**Comment by Jupeyy** [comment] 2018-02-01 12:28
probably an optical illusion, tearing increases the effect.

**Comment by heinrich5991** [comment] 2018-07-06 15:39
On ctf2 (!), I see lots of borders. I think there's something wrong. :/

**Comment by Jupeyy** [comment] 2018-07-06 16:09
can't reproduce, so probs driver

**Comment by heinrich5991** [comment] 2018-07-06 21:20
I'm on Arch Linux, with an Intel graphics card and Intel drivers:
```
$ sudo lshw -c video
  *-display                 
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:26 memory:c0000000-c03fffff memory:b0000000-bfffffff ioport:2000(size=64) memory:c0000-dffff
```

What OS/driver are you on?

**Comment by Jupeyy** [comment] 2018-07-07 02:08
debian (buster and stretch) and windows 10, nvidia.

I use the latest drivers from their website directly

I also fastly tested it with vmware mesa utils, also works.

I can't really test an intel GPU right now, bcs i don't own any myself. I tested it before without problems, but sadly not on ctf2.

What resolution are you testing in, maybe that changes anything?

**Comment by heinrich5991** [comment] 2018-07-07 06:51
1366x768

**Comment by Jupeyy** [comment] 2018-07-07 07:34
ok, still can't reproduce then. It's strange that you appearently only have this on ctf2. did you use a clean install (data directory especially).

If you would have this problem on all maps... ok, then it's pretty easy to tear down to a specific function(most probably the Mipmap not fitting the texture coordinates).

**Comment by heinrich5991** [comment] 2018-07-08 01:40
I'm sorry, you're right, this is on every map I join.

**Comment by Jupeyy** [comment] 2018-07-08 01:51
well then you can commit a bug report in the linux kernel and tell them that textureLod fails for your architecture

**Comment by heinrich5991** [comment] 2018-07-08 01:55
I definitely don't feel qualified for that.

**Comment by Jupeyy** [comment] 2018-07-08 02:20
By so many problems with such common functions, we really might consider removing the new opengl stuff again. It defenitely has benefits, but if so much hardware(especially older ones) has so much trouble with it, there no chance to get this working everywhere, because i doubt most of these driver related things gonna be fixed, and creating work arounds for everything, because some billion dollar US companies can't get a working driver, is defenitely too much xd

**Comment by def-** [comment] 2018-07-08 07:46
Well, it's off by default and marked as experimental, so I think that's fine. Some people can use it and get a benefit.

**Comment by Jupeyy** [comment] 2018-07-08 17:08
sure, it's more about the ppl that will create issues over issues. and the only thing they get as a response is "buggy driver" xD

we'll see

**Comment by Jupeyy** [comment] 2018-07-09 07:00
Revealing bugs isn't breaking something.
I only heard this problem from this n000b guy, or are there more?

**Comment by heinrich5991** [comment] 2018-08-26 20:05
This is still an issue for me.

**Comment by Jupeyy** [comment] 2018-08-26 20:10
but no issue in the code

**Comment by def-** [comment] 2018-09-11 12:51
Maybe we should just keep OpenGL3 as experimental. Doesn't seem possible to fix all bugs with all driver combinations.

**Comment by heinrich5991** [comment] 2019-06-13 23:37
![screenshot_2019-06-14_01-36-56](https://user-images.githubusercontent.com/366230/59473954-02a89100-8e45-11e9-8ed8-6106ec2c5017.png)

**Comment by Jupeyy** [comment] 2019-06-13 23:47
ok... @heinrich5991 u use linux and mesa, im sure.
pls do LIBGL_ALWAYS_SOFTWARE=true ./DDNet

and see if it happens again
btw i use 
`OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.6 (git-3b7363f499)`

thanks

**Comment by Learath2** [comment] 2019-06-13 23:49
With "Quality Textures" disabled I can consistently reproduce the lines, what does that setting do anyway? If it doesn't have a performance hit maybe we should just remove that setting.

**Comment by Jupeyy** [comment] 2019-06-13 23:51
it "manually"(own written software) downscales the textures to half size. i honestly can't tell if there is a GPU that suffers bcs of the memory bandwidth(loading textures etc).
But its possible in theory indeed

**Comment by heinrich5991** [comment] 2019-06-13 23:54
@Jupeyy That fixes the issue. It creates some new issues though, e.g. the background flickers a bit and the FPS are a lot lower (I guess that's expected if we're using a software renderer).

**Comment by Jupeyy** [comment] 2019-06-13 23:58
i experience the flicker too, but can be a bug in mesa too indeed.

i have no plan why the hell GPU drivers are soo insanly buggy for OpenGL, Sadly Vulkan is buggy too for me on AMDGPU.

The best is probably to just let it stay experimental, i am really really sure i don't do anything that isn't clearly defined in OpenGL core, it just seems like the companies trade some performance for specific precision and/or maybe its hardware specific limitations.

**Comment by fokkonaut** [comment] 2019-06-14 04:47
Join a DDNet Server anf type /map Piranha, there it is very, very noticabel

**Comment by Ryozuki** [comment] 2019-06-14 08:35
I have to say i experienced this issue, but i don't experience it any longer.

When i first experienced this issue i was on debian 9, then i moved on to debian 10 and i still noticed it, but after someday, it stopped. Now i'm on arch and i no longer see it.

Note: on debian 9 and 10 i was using the radeon driver, on arch im using amdgpu with the following kernel options:

ryozuki@arch /etc/modprobe.d $ ls
amdgpu.conf  radeon.conf
ryozuki@arch /etc/modprobe.d $ cat *
options amdgpu cik_support=1
options amdgpu si_support=0
options radeon si_support=0
options radeon cik_support=0

**Comment by Jupeyy** [comment] 2019-06-14 10:43
i said something about that map already somewhere, just search

**Closed** 2020-06-23 15:15 UTC
Labels: bug, client
