### ISSUE TITLE
./DDRace64-Server_sql: symbol lookup error: /home/teeworlds/servers/libantibot.so: undefined symbol: _Z8mem_compPKvS0_i

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6352] opened 2023-02-21 22:20 UTC
On official servers. Started after cb6879190. I'll try to bisect.

**Comment by Chairn** [comment] 2023-02-21 22:30
I believe it's caused by the change from `unsigned` to `size_t` in #6347

**Comment by def-** [comment] 2023-02-21 22:36
```
18cfbb53f9824dc35b07750302f310d1e3f66b63 is the first bad commit
commit 18cfbb53f9824dc35b07750302f310d1e3f66b63
Author: Robert Müller <robytemueller@gmail.com>
Date:   Sat Feb 4 00:39:03 2023 +0100

    Use `size_t` for `mem_*` function size parameters

 src/base/system.cpp | 13 ++++++-------
 src/base/system.h   | 10 +++++-----
 2 files changed, 11 insertions(+), 12 deletions(-)
```
Correct, so we just need to recompile libantibot probably. I don't know how to do that so running old version until @heinrich5991 or @Learath2 do that.

**Comment by heinrich5991** [comment] 2023-02-22 11:19
Fixed by recompiling the antibot. Thanks for the analysis of the root cause, @Chairn @def-. :)

**Closed by heinrich5991** 2023-02-22 11:19 UTC
