### ISSUE TITLE
/rank isn't working on LAN server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3629] opened 2021-02-17 22:19 UTC
Reported by Logunix on Discord
<img width="466" alt="ddnet_server_pqq" src="https://user-images.githubusercontent.com/2335377/108275388-8ec09f00-7176-11eb-8612-3b9f3a61050b.png">
@Zwelf any idea?

**Comment by heinrich5991** [comment] 2021-02-17 22:26
Cannot reproduce on Linux. Does it fail for anyone else on Windows?

**Comment by Zwelf** [comment] 2021-02-18 16:27
Looks like no sqlite3 file is configured. I can reproduce the failure when disabling the sqlite database:

```cfg
sv_sqlite_file ""
```

https://github.com/ddnet/ddnet/blob/1ac07fe797b7abb78d849c0bf9b010caab6c351a/src/engine/server/server.cpp#L2359

If there was a sqlite connection configured, I would at least expect a line with containing "show rank failed" before "show rank failed on all databases":
https://github.com/ddnet/ddnet/blob/1ac07fe797b7abb78d849c0bf9b010caab6c351a/src/engine/server/databases/connection_pool.cpp#L241-L242

```
[2021-02-18 17:14:24][chat-command]: 0 used /rank
[2021-02-18 17:14:24][sql]: show rank failed on all databases
```

But I have no idea what causes these weird line endings.

**Comment by heinrich5991** [comment] 2021-02-25 00:34
That's probably just threading and problems with dbg_msg.

**Comment by Robyt3** [comment] 2024-02-18 20:15
Likely caused by sqlite file not being loaded successfully. Duplicate of #6605.

**Closed by Robyt3** 2024-02-18 20:15 UTC
