### ISSUE TITLE
Proposed physics change: Handle tiles in order of touching

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6317] opened 2023-01-30 10:17 UTC
https://user-images.githubusercontent.com/2335377/215449374-da54166e-1917-4199-b7ab-775bada16469.mp4

See the attached video by tep. from Discord. 

Teleports and some other tiles are implemented in a stupid way. They are only checked once per tick, so every 20 ms. If you fly fast enough you can have been in the path of 2 different tele tiles within those 20 ms, then bad luck that the wrong one is chosen.

I think we could fix this by making sure all tiles are checked in the order they were touched during the tick, so we'd have to calculate which is earlier in the calculated flight path and prefer those. This would be a physics change but I think it would be a beneficial one. There could be complaints that it stops you from doing skips, but those skips were always annoying to do because it's not easily predictable if you will fly through a tile within a tick or not. Opinions? We could try fixing this if no one is against it.

**Comment by Learath2** [comment] 2023-01-30 10:36
I'd be in favor of changing this, but we probably need to ask testers for that one obscure map that uses it as a feature.

I thought we already made teleports unskippable, it's just that when you hit two teleports they are processed in order and you teleport to the last one instantly. I guess the fix is as simple as just stopping the iteration when we hit the first teleport tile.

**Comment by heinrich5991** [comment] 2023-01-30 11:13
I like fixing that, it will make map records unbreakable because it is actively abused there.

**Comment by heinrich5991** [comment] 2023-01-30 11:14
And don't try stuff like computing the flight path for this, just handle it during the normal collision checks, i.e. make the collision aware of teleports and stop processing the flight path on the first teleporter.

**Comment by heinrich5991** [comment] 2023-01-30 11:16
Fixed by #1264 btw.

**Comment by edg-l** [comment] 2023-01-30 11:18
This is sadly probs abused in many ranks

**Comment by def-** [comment] 2023-01-30 11:18
> I like fixing that, it will make map records unbreakable because it is actively abused there.

If a map is reported where someone believes the top rank has been done by this method, we'll have to check (manually) and delete the rank. Would be cool to have teehistorian replayer that can automatically compare if the rank still works with the physics change.

**Comment by def-** [comment] 2023-01-30 12:04
Alright, fine by me. Seems like we have everyone agreeing. Should we revive your old change @heinrich5991 ?

**Comment by heinrich5991** [comment] 2023-01-30 12:22
Duplicate of #2056.

**Closed by heinrich5991** 2023-01-30 12:22 UTC

**Comment by teini94** [comment] 2023-01-30 13:11
Suggest: Make it a "mapbug" for potential use cases.

**Comment by def-** [comment] 2023-01-30 13:38
I'm against the mapbug because there is no map using this intentionally.
