### ISSUE TITLE
the game crash

### ISSUE THREAD

**Issue by Raegulus** [ddnet/ddnet#6411] opened 2023-03-10 21:59 UTC
whenb I start it, the game crash on fisrt loading

**Comment by def-** [comment] 2023-03-10 22:12
Does this help? https://wiki.ddnet.org/wiki/GFX_Troubleshooting#Game_not_starting

**Comment by edg-l** [comment] 2023-05-13 10:35
closing because no way to reproduce was provided, open a issue if happens again

**Closed by edg-l** 2023-05-13 10:35 UTC
Labels: incomplete
