### ISSUE TITLE
Client & Server map desync

### ISSUE THREAD

**Issue by Banana090** [ddnet/ddnet#3413] opened 2020-12-15 04:42 UTC
https://www.youtube.com/watch?v=-RyhFF-PwYw

By Matodor on Discord

Join the Server at specific moment of map changing <<<

**Comment by Matodor** [comment] 2020-12-15 04:48
![image](https://user-images.githubusercontent.com/1778417/102172421-29201000-3eb2-11eb-872e-28ac45797683.png)
[milk_2020-12-15_07-06-12.zip](https://github.com/ddnet/ddnet/files/5693405/milk_2020-12-15_07-06-12.zip)

**Comment by Robyt3** [comment] 2022-11-27 11:58
Duplicate of #2804.

**Closed by Robyt3** 2022-11-27 11:58 UTC
