### ISSUE TITLE
Redirecting clients (using the servers RedirectClient) to a passworded server is buggy

### ISSUE THREAD

**Issue by swarfeya** [ddnet/ddnet#8260] opened 2024-04-24 11:32 UTC
- it shows "password incorrect", while not having entered any new password
- when entering another password, it connects back to the original server

![image](https://github.com/ddnet/ddnet/assets/135431730/f3eaa475-b442-4801-bb76-5946f30f21e2)

**Comment by Robyt3** [comment] 2024-04-24 16:13
Showing `Password incorrect` is the default behavior when connecting to any server that has a password, that's not a bug.

Pressing the `Try again` button currently uses `ui_server_address` to connect. Either we should update this config variable when redirecting, so the currently selected server in the server browser would also change when being redirected, or we should get the current server address from the engine client and reconnect to that directly instead.

**Comment by ChillerDragon** [comment] 2024-04-25 11:51
How much sense does it make to redirect to a passworded server if the user potentially does not even know which server that is.

Yes it is a bug and should be fixed for sure. But maybe we should also extend redirect messages to include a password. So if the server sends a password in the redirect message the client will use that. Or the password incorrect menu should at least show the name of the server.

**Comment by Robyt3** [comment] 2024-04-25 16:02
> But maybe we should also extend redirect messages to include a password

**Comment by Robyt3** [comment] 2024-04-25 16:03
> But maybe we should also extend redirect messages to include a password

May need a separate discussion so please open another issue for that.

**Closed** 2024-04-29 04:41 UTC
Labels: bug, client

**Comment by heinrich5991** [comment] 2024-04-29 14:55
What are you using the redirect feature for? :) @swarfeya If you mind telling.

**Comment by swarfeya** [comment] 2024-04-29 15:59
I am remaking an old mod (KoG-Level, if you know it) and I wanted to have an extra server to showcase the players with the best stats. The players are being redirected to that server when they write a command in the chat

If you want to look at it yourself, feel free to message me on discord; i'll send you the server ip/password :)
