### ISSUE TITLE
Client crash when selecting whole map to fill

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3227] opened 2020-11-01 21:40 UTC
![Base Profile Screenshot 2020 11 01 - 22 39 33 82](https://user-images.githubusercontent.com/35420825/97816118-2f0bba00-1c93-11eb-9723-af8d84a0aff9.png)

doesnt seem to happen always

**Comment by def-** [comment] 2020-11-01 21:48
Can't reproduce. Version? Your own build? Debug?

**Comment by fokkonaut** [comment] 2020-11-01 21:59
It happened on the shipped version

**Comment by Robyt3** [comment] 2022-11-06 12:55
Do you mean shift-fill? In that case this is probably the same as #5463 and already fixed by #5701.

**Comment by Robyt3** [comment] 2022-11-25 20:03
Closing as it's likely already fixed. Feel free to comment/reopen if it ever happens again.

**Closed by Robyt3** 2022-11-25 20:03 UTC
