### ISSUE TITLE
fix strong and weak indicator when sv_no_weak_hook 1

### ISSUE THREAD

**Issue by mamadof** [ddnet/ddnet#7809] opened 2024-01-15 13:48 UTC
hello :)

**Comment by heinrich5991** [comment] 2024-01-15 15:51
What do we want to do in this case? Still show the numbers but omit the strong/weak hook indicators?

**Comment by mamadof** [comment] 2024-01-15 16:00
i don't know about the numbers, but i would like to see a green indicator above all the tees if i enabled cl_nameplates_strong

**Comment by heinrich5991** [comment] 2024-01-15 16:36
I'd slightly prefer showing nothing, since showing a strong indicator everywhere doesn't really add information that's specific to the tee.

**Comment by ChillerDragon** [comment] 2024-10-01 02:52
Duplicate of https://github.com/ddnet/ddnet/issues/6141?

**Closed** 2024-10-07 16:44 UTC
