### ISSUE TITLE
DDNet do not open using OpenGL & Vulkan with Wayland Session (Flatpak version)

### ISSUE THREAD

**Issue by srdante** [ddnet/ddnet#6169] opened 2022-12-20 00:38 UTC
DDNet is not opening when using OpenGL option under a Wayland Session. This only occurs with the flatpak version. 

The Steam version is working fine.

**Comment by heinrich5991** [comment] 2022-12-20 00:42
Where does one get the flatpak version? I don't think it's built by us.

**Comment by Jupeyy** [comment] 2022-12-20 09:25
Steam probably forces xwayland and even if not, we use a bundled glew version that does not require glx. One workaround is setting DDNET_DRIVER=GLES which skips glew.
Does flathub also host Mesa drivers?

**Comment by srdante** [comment] 2022-12-29 06:22
Now it's also not working for Vulkan. Vulkan output:

```
2022-12-29 03:21:08 I sdl: SDL version 2.24.0 (compiled = 2.24.0)
2022-12-29 03:21:08 I gfx: Created Vulkan 1.1 context.
2022-12-29 03:21:09 I vulkan: initialization failed for unknown reason.
2022-12-29 03:21:09 I vulkan: vulkan error: Creating the swap chain failed.: initialization failed for unknown reason.
2022-12-29 03:21:09 I sdl: SDL version 2.24.0 (compiled = 2.24.0)
2022-12-29 03:21:09 I gfx: Created OpenGL 3.0 context.
2022-12-29 03:21:09 I gfx: setting resolution to 640x480 and trying again
2022-12-29 03:21:09 I sdl: SDL version 2.24.0 (compiled = 2.24.0)
2022-12-29 03:21:09 I gfx: Created OpenGL 3.0 context.
2022-12-29 03:21:09 I sdl: SDL version 2.24.0 (compiled = 2.24.0)
2022-12-29 03:21:09 I gfx: Created OpenGL 1.4 context.
2022-12-29 03:21:09 I gfx: out of ideas. failed to init graphics
2022-12-29 03:21:09 I client: couldn't init graphics

```

**Comment by Jupeyy** [comment] 2022-12-29 09:55
DDNET_DRIVER=GLES flatpak run tw.ddnet.ddnet 
works as expected, switching to vulkan works too.

You should note that flatpak installs own mesa drivers. if they are incompatible to your kernel drm or the host wayland libs its quite possible that it doesn't work.

Best is you use a host OS that is uses similar versions like the flatpak built. e.g. sdl 2.24.0 is used.

I'm closing this, since we neither have control over the flatpak nor is it reproducable for me

**Closed by Jupeyy** 2022-12-29 09:55 UTC

**Comment by def-** [comment] 2022-12-29 10:08
Can we detect when no OpenGL context can be created and fall back to GLES after OpenGL 1.4?

**Comment by Jupeyy** [comment] 2022-12-29 10:17
we wouldnt need GLES if glew would finally drop a new version. we can force to statically link GLEW and not rely on the system GLEW tho

**Comment by heinrich5991** [comment] 2022-12-29 14:04
Perhaps you could try reporting this bug at flathub?

**Comment by srdante** [comment] 2022-12-29 18:25
@heinrich5991 `DDNET_DRIVER=GLES flatpak run tw.ddnet.ddnet` works fine. If I switch to anything else and restart the game without the parameter, the game won't open.

**Comment by Jupeyy** [comment] 2022-12-29 21:45
well usually there is a client-like library. which flatpak ships, which is the higher level driver

but the low level, server-like part is not shipped. If there is a major breakage in the communication between both it wouldnt work.

In this case it might be the wayland session. Maybe some wayland protocol changed.
It could also be another lib.
In a worst case it could even be a new kernel feature

Ofc above assuming that it works when u run DDNet without flatpak (where the library versions match)
