### ISSUE TITLE
Request: teleport to last position instead of dying in `/practice`

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#7875] opened 2024-01-29 19:38 UTC
> QuiX — Today at 10:18 PM
> Could we change the way killtiles work in testing servers xD? Instead of killing the tee could just set it to the last position, just like /rescue 
It's hard/annoying to test maps with killtiles

**Comment by Robyt3** [comment] 2024-01-29 19:57
Duplicate of #2232.

**Closed by Robyt3** 2024-01-29 19:57 UTC
