### ISSUE TITLE
HUD should only show votes that the player can participate in.

### ISSUE THREAD

**Issue by simpygirl** [ddnet/ddnet#6235] opened 2023-01-05 20:46 UTC
As of currently, if a vote happens inside of a team. Let's say kicking a teammate to team 0, that vote will also be shown to players in other teams such as team 0 which is a bit weird as they can't vote in it.

**Comment by Robyt3** [comment] 2023-01-05 21:01
Duplicate of #2727.

**Closed by Robyt3** 2023-01-05 21:01 UTC
