### ISSUE TITLE
Client crash on start

### ISSUE THREAD

**Issue by MyNewBie** [ddnet/ddnet#840] opened 2017-08-11 06:08 UTC
windows-win32-ia32
Bam 4.0
Visual studio 2010
last ddnet source (2017/08/11)
compiler : done (CLIENT_RELEASE) build
Client crashed after seconds running. but (CLIENT_DEBUG) build work ok.

**Comment by def-** [comment] 2017-08-11 06:26
You should try cmake to build.

**Comment by MyNewBie** [comment] 2017-08-11 07:49
ok I did you said try cmake to build compiler done client work ok , but isn't it mysterious? with this way [Tutorial](https://www.teeworlds.com/forum/viewtopic.php?id=9541) client will be crash on start but with CMake build no ? absolutely something wrong I suggest u test it yourself.

**Comment by def-** [comment] 2017-08-11 08:11
I don't have Windows. We will remove the bam build soon anyway.

**Comment by MyNewBie** [comment] 2017-08-11 10:32
sorry my mistake , I compiled debug version with cmake so it work because its debug build xD , I rebuild it with release version and client crashed on start again .

**Comment by heinrich5991** [comment] 2017-08-11 10:41
What command did you use for your bam build?

How did you build DDNet with CMake? Did you create a MSVC project and compiled that in MSVC?

What is the error you get when the program "crashes"?

**Comment by def-** [comment] 2017-08-11 10:45
See also https://ddnet.tw/irclogs/2017-08-10.log

**Comment by MyNewBie** [comment] 2017-08-11 10:56
@heinrich5991 I compiled last ddnet source with two different way : 
1- compiled with bam like [Toturial](https://www.teeworlds.com/forum/viewtopic.php?id=9541)
2- compiled with CMake I create a MSVC project with that and compiled that in MSVC
both way have same result , client compiled ok without any errors only some warnings , and client crashed on start up. CLIENT_RELEASE & RELEASE what command I used for build client.
so I try to use CLIENT_DEBUG & DEBUG in both way and client compiled ok without any errors and only some warnings but in this build Client work ok run normally without crash.

**Comment by heinrich5991** [comment] 2017-08-11 12:04
What is the error you get when the program "crashes"?

**Comment by MyNewBie** [comment] 2017-08-11 12:11
nothing https://pastebin.com/AnGjWAix

**Comment by heinrich5991** [comment] 2017-08-11 12:19
Well, how do you notice the crash? Does the window go away? Is there a dialog box? ...

**Comment by MyNewBie** [comment] 2017-08-11 13:00
ok here the screenshot [Click Here](http://image.noelshack.com/fichiers/2017/32/5/1502456338-capture.png)

**Comment by heinrich5991** [comment] 2017-08-11 13:09
Could you execute the "Release" version in debug mode?

**Comment by MyNewBie** [comment] 2017-08-11 13:10
is it possible ?

**Comment by heinrich5991** [comment] 2017-08-11 13:17
With the current selection as in your screenshot (Release, Win32), you could click on the Debug menu and select "Start debugging" or so?

**Comment by MyNewBie** [comment] 2017-08-11 13:24
but It say your app not build in debug mod.

**Comment by heinrich5991** [comment] 2017-08-11 13:32
Instead of Release, can you select RelWithDebugInfo there?

**Comment by MyNewBie** [comment] 2017-08-11 13:34
ok I did with select "RelWithDebugInfo" Compiler done client run normally without crash :/

**Comment by H-M-H** [comment] 2017-08-11 20:00
This only leaves debugging with print-statements i guess. You could try to add some `dbg_msg("bughunt", "reached ...");` statements and see how far you get until the client crashes. You could start adding them about here: https://github.com/ddnet/ddnet/blob/0b1842d438bc2a789834600a17a07f098fc708bd/src/engine/client/client.cpp#L3625

If you reach  [`pClient->Run();`](https://github.com/ddnet/ddnet/blob/0b1842d438bc2a789834600a17a07f098fc708bd/src/engine/client/client.cpp#L3665) you can go on here: https://github.com/ddnet/ddnet/blob/0b1842d438bc2a789834600a17a07f098fc708bd/src/engine/client/client.cpp#L2672

Another wild guess: maybe soundloading is the problem, you could also try to disable that.

**Comment by MyNewBie** [comment] 2017-08-12 13:24
nice idea @H-M-H ok know I think I know where is the problem . after put more than 150 dbg_msg I got message from under this line [ddnet/src/engine/client/client.cpp](https://github.com/ddnet/ddnet/blob/0b1842d438bc2a789834600a17a07f098fc708bd/src/engine/client/client.cpp#L3609) seems problem from kernel.cpp I guess .

**Comment by H-M-H** [comment] 2017-08-12 22:22
@MyNewBie nice, thanks for the work you already put in into this :+1: . So lets try do narrow it down further: Can you try adding some more debug messages somewhere here and see if any of those is called: https://github.com/ddnet/ddnet/blob/0b1842d438bc2a789834600a17a07f098fc708bd/src/game/client/gameclient.cpp#L114-L264

**Comment by MyNewBie** [comment] 2017-08-13 13:12
ok as you said I put dbg_mesg after each line , seem no problem till to this line [ddnet/src/game/client/gameclient.cpp](https://github.com/ddnet/ddnet/blob/0b1842d438bc2a789834600a17a07f098fc708bd/src/game/client/gameclient.cpp#L240) Screenshot : [Click Here](http://image.noelshack.com/fichiers/2017/32/7/1502629891-bug.png)

**Comment by H-M-H** [comment] 2017-08-13 13:49
Ok, lets find out which component leads to the crash, can you please change this lines: 
https://github.com/ddnet/ddnet/blob/0b1842d438bc2a789834600a17a07f098fc708bd/src/game/client/gameclient.cpp#L239-L240
to:
```
    for(int i = 0; i < m_All.m_Num; i++)                                                                                                  
    {                                                                                                                                     
        dbg_msg("bughunt", "Initializing Component: %d", i);                                                                              
        m_All.m_paComponents[i]->OnConsoleInit();                                                                                         
    } 
```

**Comment by MyNewBie** [comment] 2017-08-13 14:45
ok I did, [Screenshot](http://image.noelshack.com/fichiers/2017/32/7/1502635502-debug.png)

**Comment by H-M-H** [comment] 2017-08-13 20:29
This is indeed suspicious, it should not go beyond 35. Does it always stop at 37 ? Can you give us the output of the debugversion with this modification ? What do you get if you put `dbg_msg("bughunt", "NumComponents: %d", m_All.m_Num);` in front of the modified loop i gave you ?

**Comment by heinrich5991** [comment] 2017-08-14 10:05
@H-M-H The log also says that some lines were skipped.

**Comment by MyNewBie** [comment] 2017-08-14 13:40
> Does it always stop at 37 ?
nope, some screenshot : [screen 01](http://www.noelshack.com/2017-33-1-1502717794-capture-01.png) , [screen 02](http://www.noelshack.com/2017-33-1-1502717796-capture-02.png) , [screen 03](http://image.noelshack.com/fichiers/2017/33/1/1502717956-capture-03.png) , [screen 04](http://image.noelshack.com/fichiers/2017/33/1/1502717956-capture-04.png) , [screen 05](http://image.noelshack.com/fichiers/2017/33/1/1502717957-capture-05.png)

**Comment by MyNewBie** [comment] 2017-08-14 13:48
> What do you get if you put  dbg_msg("bughunt", "NumComponents: %d", m_All.m_Num);  in front of the modified loop i gave you ?

ok I did this , but before that client get crashed or maybe this is " dbg_msg("bughunt", "NumComponents: %d", m_All.m_Num); "

**Comment by def-** [comment] 2017-08-14 14:11
it might be crashing into another thread?

**Comment by MyNewBie** [comment] 2017-08-14 14:17
mybe its from lasts H-M-H commits about kernel im not sure .

**Comment by H-M-H** [comment] 2017-08-14 18:24
@MyNewBie  These commits should not affect startup at all as they only do some cleanup on exit and changing fonts.
In case it is some thread started during the OnConsoleInit call that leads to the crash this might help:
```
    dbg_msg("bughunt", "NumComponents: %d", m_All.m_Num);                                                                                 
    for(int i = 0; i < m_All.m_Num; i++)                                                                                                  
    {                                                                                                                                     
        dbg_msg("bughunt", "%d", i);                                                                                                      
        m_All.m_paComponents[i]->OnConsoleInit();                                                                                         
        thread_sleep(1000);                                                                                                               
    }
```

@MyNewBie Please replace the original lines https://github.com/ddnet/ddnet/blob/0b1842d438bc2a789834600a17a07f098fc708bd/src/game/client/gameclient.cpp#L239-L240 with this (or replace the stuff i let you put there previously). And please also check what the debug version tells you and provide the output.

This is getting complicated :D

**Comment by MyNewBie** [comment] 2017-08-14 19:08
> Please replace the original lines 

ok , here the release build [screenshot](https://pastebin.com/q4mb0JkU)

> And please also check what the debug version tells you and provide the output.

and here the debug build version [screenshot](https://pastebin.com/ixtyyxSn)

> This is getting complicated :D

yep , I got heart attack xD

**Comment by savander** [comment] 2017-08-15 18:30
looks like problem with binds? :O

**Comment by MyNewBie** [comment] 2017-08-15 20:29
> looks like problem with binds component? :O

don't think so , caz I removed every thing before start the client.

**Comment by savander** [comment] 2017-08-16 11:12
I'm not saying about your binds, but about binds component. It's the last one, after that you got crash

**Comment by MyNewBie** [comment] 2017-08-18 14:24
any solution ?

**Comment by Hunter13ua** [comment] 2017-09-01 06:14
UP. DDNet 10.8.2 release crashes every time at start. Also windows defender tries to prevent new ddnet from launching. What in a world happened in 10.8.2 and why would you release that? 😞

**Comment by def-** [comment] 2017-09-01 06:23
@Hunter13ua That's a different bug and should be fixed in 10.8.3. About Windows Defender: Nothing I can do about that, try disabling firewalls and antivirus software.

**Comment by Hunter13ua** [comment] 2017-09-01 06:26
That was 10mins ago, now 10.8.3. released, no crashes and no problems with windows either.

**Comment by eeeee** [comment] 2017-09-01 08:23
There's a form to report false positives to microsoft, if we run into issues with windows defender in future.

**Comment by def-** [comment] 2017-09-01 08:30
How would you tell the difference between a real threat and a false positive? We even replace exes and dlls with downloaded stuff and execute them. How could some local software know how well we are securing the server it is downloaded from? I used to contact a few of the vendors listed on virustotal when there were problems, but gave up after some time.

**Comment by eeeee** [comment] 2017-09-01 09:16
Not that I have any experience with any of this, but I imagine if we really cared then the workflow could be:
1) we build packages (but don't release them yet)
2) check packages against virustotal, report packages as false positives to vendors of whatever triggered. (we should only really care about windows defender as I think it's the most ubiquitous and the other antivirus programs are mostly redundant these days).
3) vendors probably have some secondary semi-automated review process where they do an array of sandboxed tests with the package or something. the packages pass review and the .exe and .dll checksums are whitelisted in the signatures database updates.
4) the packages are released on ddnet.tw and for auto-update

This way they don't have to care how we're securing the servers or how the files are downloaded.

**Comment by def-** [comment] 2017-09-03 17:16
can't reproduce

**Closed by def-** 2017-09-03 17:16 UTC
