### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Veljko277** [ddnet/ddnet#6386] opened 2023-03-07 13:46 UTC
Brutal amount of random crashes

ALMOST every time i change a window via alt + tab it crashes
then when i start ddnet again it didnt remember anything

I started it with terminal it said invalid instructions

Not only was i crashing mostly on this blocker server : 185.112.83.38:8305
but i was getting lags only on this server(before it was fixed)

System:Linux
CPU:Intel® Core™ i3-10100F × 8
GPU:NVIDIA GeForce GTX 1050
Memory:12GiB
Hardware model:Gigabyte Technology Co., Ltd. H410M S2H
64 bit ; X11; Gnome 22.10
DDnet VERSION:16.8

```veljko@mining-grid-01:~/Desktop/DDNet-16.0.3-linux_x86_64$ ./DDNet
2023-03-07 14:30:44 I engine: running on unix-linux-amd64
2023-03-07 14:30:44 I engine: arch is little endian
2023-03-07 14:30:44 I engine: operation system version: Linux 5.19.0-35-generic (x86_64, #36-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 3 18:36:56 UTC 2023); "Ubuntu 22.10"
2023-03-07 14:30:44 I storage: added path '$USERDIR' ('/home/veljko/.teeworlds')
2023-03-07 14:30:44 I storage: added path '$DATADIR' ('data')
2023-03-07 14:30:44 I storage: added path '$CURRENTDIR' ('/home/veljko/Desktop/DDNet-16.0.3-linux_x86_64')
2023-03-07 14:30:44 I discord: error initializing discord instance, error=4
2023-03-07 14:30:44 I http: libcurl version 7.85.0 (compiled = 7.84.0)
2023-03-07 14:30:44 I console: executing 'settings_ddnet.cfg'
2023-03-07 14:30:44 I client: adding 37.230.162.88:8303 to favorites
2023-03-07 14:30:44 I client: starting...
2023-03-07 14:30:44 I sdl: SDL version 2.24.0 (compiled = 2.0.6)
2023-03-07 14:30:44 I gfx: Created Vulkan 1.1 context.
2023-03-07 14:30:44 I gfx: GPU vendor: NVIDIA
2023-03-07 14:30:44 I gfx: GPU renderer: NVIDIA GeForce GTX 1050
2023-03-07 14:30:44 I gfx: GPU version: Vulkan 1.3.205 (driver: 515.86.1.0)
2023-03-07 14:30:44 I freetype: freetype version 2.12.1 (compiled = 2.9.1)
2023-03-07 14:30:44 I textrender: loaded font from 'data/fonts/Icons.otf'
2023-03-07 14:30:44 I joystick: 0 joystick(s) found
2023-03-07 14:30:44 I textrender: loaded font from 'data/fonts/DejaVuSans.ttf'
2023-03-07 14:30:44 I textrender: loaded fallback font from 'data/fonts/GlowSansJCompressed-Book.otf'
2023-03-07 14:30:44 I textrender: loaded fallback font from 'data/fonts/SourceHanSansSC-Regular.otf'
2023-03-07 14:30:44 I textrender: default font set to 'data/fonts/DejaVuSans.ttf'
2023-03-07 14:30:44 I datafile: could not open 'themes/newyear_day.map'
2023-03-07 14:30:44 I client: version 16.8 on linux amd64
2023-03-07 14:30:44 I http: fetching https://info.ddnet.org/info?name=VekiPro
2023-03-07 14:30:44 I http: task done https://info.ddnet.org/info?name=VekiPro
2023-03-07 14:30:46 I http: https://master4.ddnet.org/ddnet/15/servers.json failed. libcurl error (6): Could not resolve host: master4.ddnet.org
2023-03-07 14:30:47 I http: fetching https://master1.ddnet.org/ddnet/15/servers.json
2023-03-07 14:30:47 I http: task done https://master1.ddnet.org/ddnet/15/servers.json
2023-03-07 14:30:48 I http: https://master3.ddnet.org/ddnet/15/servers.json failed. libcurl error (6): Could not resolve host: master3.ddnet.org
2023-03-07 14:30:49 I client: connecting to '185.112.83.38:8305'
2023-03-07 14:30:49 I host_lookup: host='185.112.83.38' port=8305 3
2023-03-07 14:30:49 I client: connected, sending info
2023-03-07 14:30:49 I datafile: could not open 'maps/Copy Love Box 2s.map'
2023-03-07 14:30:49 I http: https://master2.ddnet.org/ddnet/15/servers.json failed. libcurl error (22): The requested URL returned error: 404
2023-03-07 14:30:49 I motd: 
2023-03-07 14:30:49 I motd: [ONLINE SUPPORTER]:
2023-03-07 14:30:49 I motd: • 'Kisao'
2023-03-07 14:30:50 I serverbrowse_http: found master, url='https://master1.ddnet.org/ddnet/15/servers.json' time=98ms
2023-03-07 14:30:50 I serverbrowse_http: determined best master, url='https://master1.ddnet.org/ddnet/15/servers.json' time=98ms
2023-03-07 14:30:50 I tune: switch_open 1
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chatresp: No such command: switch_open.
2023-03-07 14:30:50 I chat: *** [+] (2)VekiPro
2023-03-07 14:30:50 I chat: *** 16.7.1
2023-03-07 14:30:50 I chat: *** Welcome to the club buddy ♥
2023-03-07 14:30:50 I demo_recorder: Recording to 'demos/auto/Copy Love Box 2s_2023-03-07_14-30-50.demo'
2023-03-07 14:30:50 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:30:50 I client: got pong from current server, latency=78ms
2023-03-07 14:30:51 I chat: *** 'koiloo' is on a blocking spree with 5 kills!
2023-03-07 14:30:52 I chat: *** [-] ты никто
2023-03-07 14:30:52 I chat: *** [-] qqk
2023-03-07 14:30:53 I demo_recorder: Stopped recording
2023-03-07 14:30:53 I chat: *** [-] (2)VekiPro (Timeout Protection used)
2023-03-07 14:30:53 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:30:54 I demo_recorder: Stopped recording
2023-03-07 14:30:54 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:30:55 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:30:57 I chat: *** 'herblyat's blocking spree was ended by 'VekiPro' (10 Kills)
2023-03-07 14:30:58 I chat: *** You are now in a solo part
2023-03-07 14:30:59 I demo_recorder: Stopped recording
2023-03-07 14:30:59 I ghost_recorder: Stopped ghost recording
2023-03-07 14:30:59 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:31:00 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:02 I chat: Krxbol x Karlo1: ???: war?
2023-03-07 14:31:02 I chat: *** You are now in a solo part
2023-03-07 14:31:06 I demo_recorder: Stopped recording
2023-03-07 14:31:06 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:06 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:31:07 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:09 I chat: *** You are now in a solo part
2023-03-07 14:31:13 I chat: Krxbol x Karlo1: !addwar ??? {podsos}
2023-03-07 14:31:14 I demo_recorder: Stopped recording
2023-03-07 14:31:14 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:14 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:31:16 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:16 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:16 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:20 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:20 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:21 I demo_recorder: Stopped recording
2023-03-07 14:31:21 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:21 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:31:22 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:23 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:23 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:23 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:23 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:26 I chat: *** You are now in a solo part
2023-03-07 14:31:28 I chat: OHHHHHHHHHHHHHH: ujkbg
2023-03-07 14:31:30 I chat: OHHHHHHHHHHHHHH: голип
2023-03-07 14:31:31 I chat: OHHHHHHHHHHHHHH: пон
2023-03-07 14:31:37 I demo_recorder: Stopped recording
2023-03-07 14:31:37 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:37 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:31:38 I chat: Krxbol x Karlo1: herblyat: я твою мать в кишечник трахал
2023-03-07 14:31:39 I chat: *** [+] (1)sus boi
2023-03-07 14:31:39 I chat: *** 16.7.1
2023-03-07 14:31:39 I chat: *** Welcome to the club buddy ♥
2023-03-07 14:31:39 I chat: OHHHHHHHHHHHHHH: БЕБНА:
2023-03-07 14:31:39 I demo_recorder: Stopped recording
2023-03-07 14:31:39 I demo_recorder: Recording to 'demos/auto/Copy Love Box 2s_2023-03-07_14-31-39.demo'
2023-03-07 14:31:39 I client: got pong from current server, latency=75ms
2023-03-07 14:31:40 I chat: OHHHHHHHHHHHHHH: справа
2023-03-07 14:31:41 I chat: *** [-] (1)sus boi (Timeout Protection used)
2023-03-07 14:31:42 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:43 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:43 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:31:47 I ghost_recorder: Stopped ghost recording
2023-03-07 14:31:47 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:32:06 I chat: *** 'koiloo's blocking spree was ended by 'Kisao' (5 Kills)
2023-03-07 14:32:11 I chat: To HoMe: ????
2023-03-07 14:32:12 I chat: eRRoR 404: алё блять
2023-03-07 14:32:16 I chat: ᴇʟɪᴇᴡ: че блять
2023-03-07 14:32:16 I chat: eRRoR 404: kisao
2023-03-07 14:32:17 I chat: Krxbol x Karlo1: 10 0
2023-03-07 14:32:18 I chat: *** [+] [D] roman13rogo
2023-03-07 14:32:18 I chat: Kisao: eRRoR 404: че
2023-03-07 14:32:19 I chat: eRRoR 404: ну чё началось
2023-03-07 14:32:20 I chat: daniil2597: чо бл происходит?
2023-03-07 14:32:30 I ghost_recorder: Stopped ghost recording
2023-03-07 14:32:30 I demo_recorder: Stopped recording
2023-03-07 14:32:30 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:32:30 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:32:31 I ghost_recorder: Stopped ghost recording
2023-03-07 14:32:31 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:32:31 I chat: OHHHHHHHHHHHHHH: ЧЕ
2023-03-07 14:32:32 I chat: *** VekiPro: Нажми F4 что бы начать разговор.
2023-03-07 14:32:36 I chat: *** Ма ас-салама!
2023-03-07 14:32:39 I ghost_recorder: Stopped ghost recording
2023-03-07 14:32:39 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:32:45 I chat: *** 'herblyat' is on a blocking spree with 5 kills!
2023-03-07 14:32:45 I chat: daniil2597: 0-0
2023-03-07 14:32:46 I demo_recorder: Stopped recording
2023-03-07 14:32:46 I ghost_recorder: Stopped ghost recording
2023-03-07 14:32:46 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:32:47 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:32:47 I chat: Vlad_reg: wtf
2023-03-07 14:32:47 I chat: *** [+] ʙɪʙɪ❤
2023-03-07 14:32:49 I chat: Skvizzyyy x top: да вийграю
2023-03-07 14:32:51 I chat: eRRoR 404: ЧТО ЗА ХУЙНЯ
2023-03-07 14:32:53 I chat: Krxbol x Karlo1: Kisao: реквизиты кидай я премку покупаю
2023-03-07 14:32:53 I chat: ᴇʟɪᴇᴡ: ХАХАХАХА
2023-03-07 14:32:56 I chat: *** 'herblyat's blocking spree was ended by 'daniil2597' (7 Kills)
2023-03-07 14:32:56 I chat: *** [+] санёк
2023-03-07 14:32:57 I chat: daniil2597: 0-0
2023-03-07 14:32:59 I demo_recorder: Stopped recording
2023-03-07 14:32:59 I ghost_recorder: Stopped ghost recording
2023-03-07 14:32:59 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:33:00 I chat: daniil2597: ХАХАХАХАХАХ
2023-03-07 14:33:01 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:33:01 I ghost_recorder: Stopped ghost recording
2023-03-07 14:33:02 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:33:02 I chat: Vlad_reg: wtf  blat
2023-03-07 14:33:03 I chat: *** [-] санёк
2023-03-07 14:33:03 I chat: *** [+] rab Skvizzyyy
2023-03-07 14:33:03 I chat: Kisao: Krxbol x Karlo1: чееееееееее
2023-03-07 14:33:03 I ghost_recorder: Stopped ghost recording
2023-03-07 14:33:03 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:33:04 I chat: eRRoR 404: xD
2023-03-07 14:33:06 I chat: *** [+] [D] Vlad_reg
2023-03-07 14:33:07 I demo_recorder: Stopped recording
2023-03-07 14:33:07 I ghost_recorder: Stopped ghost recording
2023-03-07 14:33:07 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:33:08 I chat: ᴇʟɪᴇᴡ: SORRY To HoMe
2023-03-07 14:33:08 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:33:13 I chat: *** [-] Dummy
2023-03-07 14:33:19 I chat: *** [+] Humansuit
2023-03-07 14:33:24 I chat: *** [+] 0fexx1.xo
2023-03-07 14:33:29 I chat: *** [-] [D] Vlad_reg
2023-03-07 14:33:31 I chat: *** 'fr0st' is on a blocking spree with 15 kills!
2023-03-07 14:33:33 I ghost_recorder: Stopped ghost recording
2023-03-07 14:33:33 I demo_recorder: Stopped recording
2023-03-07 14:33:33 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:33:33 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:33:35 I chat: *** [+] Dummy
2023-03-07 14:33:36 I demo_recorder: Stopped recording
2023-03-07 14:33:36 I ghost_recorder: Stopped ghost recording
2023-03-07 14:33:36 I demo_recorder: Recording to 'demos/auto/race/Copy Love Box 2s_tmp_18726.demo'
2023-03-07 14:33:37 I chat: *** [-] Dummy
2023-03-07 14:33:40 I chat: Kisao: Krxbol x Karlo1: в дс напиши
2023-03-07 14:33:41 I chat: *** [+] anal.hicsaa
2023-03-07 14:33:42 I chat: OHHHHHHHHHHHHHH: {D}БЕБНА:  учись
2023-03-07 14:33:42 I chat: *** 'ykk1n' is on a blocking spree with 5 kills!
2023-03-07 14:33:43 I chat: OHHHHHHHHHHHHHH: ахвахвх
2023-03-07 14:33:44 I ghost_recorder: ghost recording to 'ghosts/Copy Love Box 2s_VekiPro_7f645b854df2a9f809d759b1f7363cbcf2c03684105bd8326cb6e11308aede7f_tmp_18726.gho'
2023-03-07 14:33:50 I chat: Vlad_reg: ,,,
2023-03-07 14:33:51 I chat: *** [+] lilkikcek
2023-03-07 14:33:55 I chat: Vlad_reg: idiot
2023-03-07 14:34:05 I chat: eRRoR 404: блять
2023-03-07 14:34:08 I chat: *** [+] [D] Vlad_reg
2023-03-07 14:34:11 I chat: eRRoR 404: БЕБНА: - молот
2023-03-07 14:34:11 I chat: Krxbol x Karlo1: Kisao: ну ты крутой конечно. сначало разблокируй и на кио разбань
2023-03-07 14:34:19 I chat: Kisao: Krxbol x Karlo1: так дс то есть у тебя мой
2023-03-07 14:34:23 I chat: eRRoR 404: Kisao: чё ты там химичиш
2023-03-07 14:34:27 I chat: Krxbol x Karlo1: Kisao: -
2023-03-07 14:34:34 I chat: Kisao: Krxbol x Karlo1: ты лс удалил?
2023-03-07 14:34:34 I chat: *** [-] [D] Vlad_reg
2023-03-07 14:34:38 I chat: *** 'Solar' is on a blocking spree with 5 kills!
2023-03-07 14:34:45 I chat: Krxbol x Karlo1: Kisao: да. зачем мне лишний мусор
2023-03-07 14:34:47 I chat: Kisao: Krxbol x Karlo1: на дс сервере я тебя уже давно разбанил :D
2023-03-07 14:34:53 I chat: *** 'herblyat' is on a blocking spree with 5 kills!
2023-03-07 14:34:57 I chat: *** [-] rab Skvizzyyy
2023-03-07 14:35:22 I chat: *** [+] 3x1sT
2023-03-07 14:35:27 I chat: simagey2122: ой
2023-03-07 14:35:34 I chat: 0fexx1.xo: eRRoR 404: war life yebiche
2023-03-07 14:35:43 I chat: eRRoR 404: 0fexx1.xo: непизди
2023-03-07 14:35:45 I chat: *** [-] ʙɪʙɪ❤
2023-03-07 14:35:50 I chat: *** 'herblyat's blocking spree was ended by 'anal.hicsaa' (6 Kills)
2023-03-07 14:36:05 I chat: *** 'Krxbol x Karlo1' called vote to change server option 'Discord: https://discord.gg/z5yncu3pMu' (No reason given)
2023-03-07 14:36:06 I chat: *** [-] To HoMe
2023-03-07 14:36:08 I textrender: Found non empty text container with index 368 with 10 quads
2023-03-07 14:36:08 I assert: /ddnet-source/src/engine/client/text.cpp(1945): text container was not empty
Неисправна инструкција
```

**Comment by Jupeyy** [comment] 2023-03-07 17:16
no chance to reproduce it for me, really weird

**Comment by Robyt3** [comment] 2023-03-09 20:22
Duplicate of #5143, let's keep the discussion over there.

**Closed by Robyt3** 2023-03-09 20:22 UTC
