### ISSUE TITLE
Open website fails and hangs Steam on Linux

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3060] opened 2020-10-11 09:20 UTC
Reported by @Jupeyy

**Comment by heinrich5991** [comment] 2020-10-11 15:32
Can't reproduce on DDNet on Steam on Linux, open the website fine in Firefox.

**Comment by edg-l** [comment] 2021-08-14 12:08
can't reproduce too, closing for now, feel free to reopen if it happens

**Closed by edg-l** 2021-08-14 12:08 UTC
