### ISSUE TITLE
Add possibility of translation

### ISSUE THREAD

**Issue by CasualTomato** [ddnet/ddnet#7479] opened 2023-11-16 18:59 UTC
Part of the window has been translated, but the main message remains not localized.

![image](https://github.com/ddnet/ddnet/assets/151072351/e5cbb656-cf4e-4a64-9e9f-d02a368f0eee)

**Comment by heinrich5991** [comment] 2023-11-16 21:04
Duplicate of #3091.

**Closed by heinrich5991** 2023-11-16 21:04 UTC

**Comment by furo321** [comment] 2023-11-16 21:17
Why close? This message isn't sent by the server.

**Comment by heinrich5991** [comment] 2023-11-16 21:21
Oh right, I forgot that.

It's also sent by the server. And the client-sent one would probably use the same mechanism as the server-sent one, I guess.
