### ISSUE TITLE
Dummy for muiltiple servers

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1305] opened 2018-09-27 19:27 UTC
https://github.com/ddnet/ddnet/issues/1212

@def- many people like this and want it to be implemented to ddnet

**Comment by Learath2** [comment] 2018-09-28 12:58
I don't particularly like this idea either, I don't think it fits in a generic client. What will you even be doing with this feature?

(Off-topic: does your keyboard not have a shift key?)

**Comment by fokkonaut** [comment] 2018-09-28 13:00
xD it does have^^

**Comment by def-** [comment] 2018-09-28 13:38
Duplicate of #1212

**Closed by def-** 2018-09-28 13:38 UTC
