### ISSUE TITLE
Browser shows servers from another tab

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2712] opened 2020-09-02 16:18 UTC
How to reproduce:
1. Set Maximum ping to 999 in filters
2. Select DDNet tab
3. Press F5(refresh browser bind) and click on the LAN page almost in the same time (you got to be VERY fast here)

![image](https://user-images.githubusercontent.com/17499770/92008748-37f21500-ed50-11ea-8cd3-50b9bafa1fc7.png)

**Comment by def-** [comment] 2020-09-02 16:21
Duplicate of #2620

**Closed by def-** 2020-09-02 16:21 UTC
