### ISSUE TITLE
does /save not keep hook...

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2507] opened 2020-07-13 10:01 UTC
As reported by Clavata on Discord. @Zwelf ?

**Comment by heinrich5991** [comment] 2020-07-13 10:31
Info: The old behavior was that /save does not keep hook. I think we changed it to keep hook.

**Comment by Zwelf** [comment] 2020-07-13 10:40
The client has to send `m_Hook = true` in the PlayerInput struct while loading. Otherwise the hook is released immediately after loading. When the tee is in pause mode, the hook is kept at least until unpausing. (If everything works as I tested it in #2424)

**Comment by def-** [comment] 2020-07-13 11:36
I think this is a bit too strict, because who can remember if they were hooking when they saved and remember to hook again when loading? Maybe we should just save the hook state and keep hooked throughout the save and also stay hooked afterwards. Is that possible?

**Comment by heinrich5991** [comment] 2020-07-13 11:58
I think we shouldn't add faking input for the client. I think it would complicate the code too much (with the usual consequences: harder to debug, easier for bugs to slip in, harder to change).

> Maybe we should just save the hook state and keep hooked throughout the save and also stay hooked afterwards.

(We do save the hook.)

**Comment by def-** [comment] 2020-07-13 13:52
This happened on the map RON, which requires you to keep hook held all the time.

**Comment by Learath2** [comment] 2020-07-13 13:59
This should behave the same way holding hook while getting into chat behaves

**Comment by heinrich5991** [comment] 2020-07-13 14:02
> This should behave the same way holding hook while getting into chat behaves

It does: Hook is released when the client stops sending the hook.

**Comment by Learath2** [comment] 2020-07-13 14:05
If you go into chat while hooking, let go and stop chatting, it won't just
drop you

**Comment by heinrich5991** [comment] 2020-07-13 14:14
Okay, I thought this was some implementation guideline. The fix for this would be completely different from the one with chat.

**Comment by Learath2** [comment] 2020-07-13 14:25
Would it? We just need to get the tees that are hooked into that state
while loading

**Comment by heinrich5991** [comment] 2020-07-13 14:49
Yes it would. What you describe is the current state. The problem is that the client sends that there it doesn't currently hook. Thus the server releases the hook after loading.

**Comment by kamillentee** [comment] 2021-03-11 05:35
Should be closed

**Closed** 2021-03-11 09:16 UTC
Labels: bug, server
