### ISSUE TITLE
Collision problem on server

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#6623] opened 2023-05-19 13:11 UTC
When you jump to a solid tile's side(like this):

![like](https://github.com/ddnet/ddnet/assets/65482653/4e897450-933d-4e4f-866c-b1bc4348cb6b)

Sometimes you will cannot move.
The problem is solved after the jump.

**Comment by def-** [comment] 2023-05-19 15:02
I'm afraid I don't understand, can you post a video? Is that on current DDNet server (what version)?

**Comment by RemakePower** [comment] 2023-05-20 10:28
> I'm afraid I don't understand, can you post a video? Is that on current DDNet server (what version)?

Sorry i don't have any video. But it's a official DDNet server bug.

**Comment by murpii** [comment] 2023-05-21 13:16
> > I'm afraid I don't understand, can you post a video? Is that on current DDNet server (what version)?
> 
> Sorry i don't have any video. But it's a official DDNet server bug.

A demo would also suffice. Do you remember the name of the map where this happened?

**Comment by RemakePower** [comment] 2023-05-22 10:51
> > > I'm afraid I don't understand, can you post a video? Is that on current DDNet server (what version)?
> > 
> > 
> > Sorry i don't have any video. But it's a official DDNet server bug.
> 
> A demo would also suffice. Do you remember the name of the map where this happened?

I remember I once saw someone post a video about this bug on a Chinese website, but I can't find it now.
This bug is happened on every map.

**Comment by hus3h** [comment] 2023-05-22 21:55
Probably talking about magic edge?

@RemakePower is it like what happens in these videos?

https://cdn.discordapp.com/attachments/295908390956433410/1071514794198319134/RON_2023-02-04_22-34-19.demo.mp4

https://cdn.discordapp.com/attachments/295908390956433410/1020385565687939082/GrandmaSTUCK.demo.mp4

**Comment by Robyt3** [comment] 2023-12-02 10:48
Likely a duplicate of #1738.

**Closed by Robyt3** 2023-12-02 10:48 UTC
