### ISSUE TITLE
New Feature: Add personal client-sided time Checkpoints

### ISSUE THREAD

**Issue by aschur123** [ddnet/ddnet#1908] opened 2019-09-15 04:11 UTC
there are time checkpoints on some maps but not on all maps. they are useful for speedruns and it would be cool if i can add my own timecheckpoints and place them where i want.

**Comment by heinrich5991** [comment] 2019-09-15 12:51
@12pm Would you accept a map change only adding time checkpoints?

**Comment by 12pm** [comment] 2019-09-15 13:28
in general it's not worth it imo. you don't gain much since people mostly speedrun maps when they are released.

**Comment by aschur123** [comment] 2019-09-15 13:34
if you look in the ddnet records, not only new maps are getting speedrunned. makes no sense that you said that.
it would be cool if players can add their timecps in the mapeditor and save it.

**Comment by 12pm** [comment] 2019-09-15 13:51
i said "mostly". basically you're trading an extra download and map file for a small advatange for a few speedrunners (who are a minority anyways)

**Comment by Learath2** [comment] 2019-10-25 01:42
I was working on adding a separate file that added checkpoints to maps so that the maps themselves didn't all need to be updated and the demos wouldn't become invalid. Turns out to be way too much work.

**Comment by C0D3D3V** [comment] 2022-06-06 13:46
This is kind of the same request as in https://github.com/ddnet/ddnet/issues/5336

We decided to try to add on all maps time checkpoints.

**Comment by Robyt3** [comment] 2023-12-30 17:05
Duplicate of #5336. Checkpoints are being added to all maps.

**Closed by Robyt3** 2023-12-30 17:05 UTC
Labels: enhancement, client
