### ISSUE TITLE
DDNet 15.5.4 from Ubuntu 21.10 can't show servers proprerly

### ISSUE THREAD

**Issue by StarOnTheSky** [ddnet/ddnet#4202] opened 2021-10-07 02:31 UTC
OS Version: Ubuntu 21.10 x86_64
DDNet Version: 15.5.4-1ubuntu1
Problem:
![Screenshot_20211007_102341](https://user-images.githubusercontent.com/51866924/136310610-66b4e4c5-bc62-48d5-b727-ab01b24fff4a.png)
Servers cannot be showed properly.
P.S. DDNet downloaded from https://ddnet.tw/ works properly on my computer.

**Comment by def-** [comment] 2021-10-07 07:13
Do you have some server filter set on the right side?

Is your firewall blocking access to https://master1.ddnet.tw/ddnet/15/servers.json ?

**Comment by StarOnTheSky** [comment] 2021-10-07 12:23
> Do you have some server filter set on the right side?
> 
> Is your firewall blocking access to https://master1.ddnet.tw/ddnet/15/servers.json ?

No server filter is set.
This link is accessible on my computer (DDNet package downloaded from https://ddnet.tw/ works properly).

**Comment by def-** [comment] 2021-10-16 16:30
That's really weird, can you run it from command line and show the entire console output there?

**Comment by StarOnTheSky** [comment] 2021-10-16 22:32
> That's really weird, can you run it from command line and show the entire console output there?

https://asciinema.org/a/mlIb9CSo6aBzJAzjNyMOqmQ8G

**Comment by StarOnTheSky** [comment] 2021-10-16 22:41
> That's really weird, can you run it from command line and show the entire console output there?

Also, on my computer, I can't connect to the external servers through my Wi-Fi connection. I have to connect them through wired connection. That's a really a big trouble because I have no Ethernet cables now and I can't connect to any server except localhost. Any other application requiring Ethernet connection works fine on my computer such as Firefox.

**Comment by hus3h** [comment] 2021-11-17 13:32
Hello,

I am using Fedora 34 with everything up-to-date, with DDNet installed from the distribution packages using DNF. I had this problem with 15.5.4 and still having it now with 15.6.2 installed from the testing repository. I tested the version from the website downloads on the same device before and it did not have this problem.

DDNet Fedora packages: https://src.fedoraproject.org/rpms/ddnet/

**Comment by def-** [comment] 2021-11-17 13:41
Can you show the full command line output?

**Comment by hus3h** [comment] 2021-11-17 14:08
Sure!

I launched the game with DDNet tab selected from last time and then closed it.
I only removed the lines about binds to make the long output shorter. Let me know if they are needed.

`
2021-11-17 15:59:14][engine]: running on unix-linux-amd64
2021-11-17 15:59:14][engine]: arch is little endian
2021-11-17 15:59:14][storage]: couldn't open storage.cfg
2021-11-17 15:59:14][storage]: using standard paths
2021-11-17 15:59:14][storage]: added path '$USERDIR' ('/home/user/.teeworlds')
2021-11-17 15:59:14][storage]: added path '$DATADIR' ('/usr/share/ddnet/data')
2021-11-17 15:59:14][storage]: added path '$CURRENTDIR' ('/home/user')



2021-11-17 15:59:14][http]: libcurl version 7.76.1 (compiled = 7.76.1)
2021-11-17 15:59:14][console]: executing 'settings_ddnet.cfg'
2021-11-17 15:59:14][demorec/record]: client is not online
2021-11-17 15:59:14][demorec/record]: client is not online



2021-11-17 15:59:14][client]: starting...
2021-11-17 15:59:14][sdl]: SDL version 2.0.16 (compiled = 2.0.16)
2021-11-17 15:59:14][gfx]: Created OpenGL 3.0 context.
2021-11-17 15:59:14][opengl]: Vendor string: Intel
2021-11-17 15:59:14][opengl]: Version string: 4.6 (Compatibility Profile) Mesa 21.1.8
2021-11-17 15:59:14][gfx]: GPU vendor: Intel
2021-11-17 15:59:14][gfx]: GPU renderer: Mesa Intel(R) UHD Graphics (CML GT2)
2021-11-17 15:59:14][gfx]: GPU version: 4.6 (Compatibility Profile) Mesa 21.1.8
2021-11-17 15:59:14][client/sound]: sound init successful using audio driver 'pulseaudio'
2021-11-17 15:59:14][freetype]: freetype version 2.10.4 (compiled = 2.10.4)
2021-11-17 15:59:14][textrender]: loaded pFont from '/usr/share/ddnet/data/fonts/Icons.ttf'
2021-11-17 15:59:14][textrender]: loaded pFont from '/usr/share/ddnet/data/fonts/DejaVuSans.ttf'
2021-11-17 15:59:14][textrender]: loaded fallback font from '/usr/share/ddnet/data/fonts/GlowSansJCompressed-Book.otf'
2021-11-17 15:59:14][textrender]: loaded fallback font from '/usr/share/ddnet/data/fonts/SourceHanSansSC-Regular.otf'
2021-11-17 15:59:14][textrender]: default pFont set 0x5565aac7e6e0
2021-11-17 15:59:15][gameclient]: initialisation finished after 908.62ms
2021-11-17 15:59:15][client]: version 0.6 626fce9a778df4d4
2021-11-17 15:59:15][http]: fetching https://info2.ddnet.tw/info
2021-11-17 15:59:16][http]: task done https://info2.ddnet.tw/info
2021-11-17 15:59:16][http]: fetching https://master1.ddnet.tw/ddnet/15/servers.json
2021-11-17 15:59:16][serverbrowse_http]: found master, url='https://master1.ddnet.tw/ddnet/15/servers.json' time=271ms
2021-11-17 15:59:16][http]: https://master3.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Could not resolve host: master3.ddnet.tw
2021-11-17 15:59:17][http]: task done https://master1.ddnet.tw/ddnet/15/servers.json
2021-11-17 15:59:18][serverbrowse_http]: found master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=923ms
2021-11-17 15:59:18][http]: https://master4.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Could not resolve host: master4.ddnet.tw
2021-11-17 15:59:18][serverbrowse_http]: determined best master, url='https://master1.ddnet.tw/ddnet/15/servers.json' time=271ms
2021-11-17 15:59:20][client]: disconnecting. reason='unknown'
2021-11-17 15:59:20][storage]: failed to remove: /home/user/.teeworlds/
`

**Comment by StarOnTheSky** [comment] 2021-11-17 15:06
> Can you show the full command line output of running DDNet

This problem persists as Ubuntu, or Debian, never upgrade the non-essential softwares' versions.

**Comment by hus3h** [comment] 2021-11-17 16:42
Yes I just tried, it created the new directory and all but sadly the servers list is still showing the same way.

**Comment by def-** [comment] 2021-11-17 16:54
Can you share a screenshot with the filter screen shown?

**Comment by hus3h** [comment] 2021-11-17 17:04
This is a screenshot taken directly after launching the game with no .teeworlds directory so everything should be on default value.

![index](https://user-images.githubusercontent.com/39054982/142246937-deddb49b-5919-48bf-b4e8-9b9313a55e90.png)

**Comment by def-** [comment] 2021-11-17 17:06
Both Debian/Ubuntu and Fedora use a system libjsonparser instead of the one we ship with. I can imagine that this is causing the problem.

**Comment by def-** [comment] 2021-11-17 17:12
Got it reproduced, it's indeed their libjsonparser that doesn't work, since it doesn't contain our change:
```
         /* DDNet additions */
         inline operator int () const
         {   
            return (json_int_t) *this;
         }
```

**Comment by hus3h** [comment] 2021-11-17 17:15
Oh great to know! This is a screenshot showing json-parser being a dependency for ddnet package with the version in case that helps.

![image](https://user-images.githubusercontent.com/39054982/142248751-caffdf5f-14b8-446b-a09f-0b65671d2c41.png)

Thanks for all the efforts!

**Comment by heinrich5991** [comment] 2021-11-17 19:41
Reopening since we need to fix this on Fedora and Ubuntu. I guess that means contacting the maintainers?

**Comment by StarOnTheSky** [comment] 2021-11-17 22:28
> Reopening since we need to fix this on Fedora and Ubuntu. I guess that means contacting the maintainers?

Yes, these packages need to be repacked.

**Comment by def-** [comment] 2021-11-17 22:28
Yes, I will do that.

**Comment by StarOnTheSky** [comment] 2021-11-17 22:31
> Both Debian/Ubuntu and Fedora use a system libjsonparser instead of the one we ship with. I can imagine that this is causing the problem.

But everything works well in the binary compiled with 100% system libraries.

**Comment by def-** [comment] 2021-11-17 22:32
Actually @yangfl for Debian might be around: Can we get all DDNet Debian versions with system libjsonparser rereleased with this fix? https://github.com/ddnet/ddnet/pull/4357

**Comment by def-** [comment] 2021-11-17 22:33
@ElXreno Same question but for Fedora ^

**Comment by ElXreno** [comment] 2021-11-18 10:40
Unfortunately, I no longer support DDNet in Fedora. But I can send a fix to the new maintainer to get this fixed as soon as possible.

**Comment by def-** [comment] 2021-11-18 11:15
Ok, too bad. The fedora website was not loading for me yesterday, so I couldn't check the current maintainer. Thanks for the help!

**Comment by ElXreno** [comment] 2021-11-19 16:22
Commit [accepted](https://src.fedoraproject.org/rpms/ddnet/c/3dad07e6638473321afcd0f482560cec3cf4d660?branch=rawhide) and [mostly pushed](https://bodhi.fedoraproject.org/updates/FEDORA-2021-c5336b90e7) to testing!

**Comment by hus3h** [comment] 2021-11-20 06:56
I updated using the testing repository and things seem to be working just fine.

Only concern is, as mentioned in #4357, the old versions in the repositories not getting the fix which will keep them broken for some time.

![Screenshot from 2021-11-20 08-48-59](https://user-images.githubusercontent.com/39054982/142717546-fcf24d4e-9939-4cca-ae48-59c02f04c840.png)

**Comment by StarOnTheSky** [comment] 2021-11-20 08:43
> Ok, too bad. The fedora website was not loading for me yesterday, so I couldn't check the current maintainer. Thanks for the help!

So do you know whether and when will Debian & Ubuntu accept this bugfix update?

**Comment by def-** [comment] 2021-11-20 09:33
Yangfl responded that he'll wait for next version (I think). So in 6 days we should release DDNet 15.7 and then it'll be fixed in Debian + Ubuntu too.

**Comment by StarOnTheSky** [comment] 2021-11-20 12:00
> Yangfl responded that he'll wait for next version (I think). So in 6 days we should release DDNet 15.7 and then it'll be fixed in Debian + Ubuntu too.

I don't think so. As a non-essential package, Ubuntu & Debian's stable releases won't contain DDNet's new releases. For example, DDNet from Ubuntu 21.10 (latest stable release) is still in version 15.5.4 .

**Comment by def-** [comment] 2021-11-20 12:14
Ok, I opened a ubuntu bug to speed this up: https://bugs.launchpad.net/ubuntu/+source/ddnet/+bug/1951680

**Comment by StarOnTheSky** [comment] 2021-11-23 22:22
> Ok, I opened a ubuntu bug to speed this up: https://bugs.launchpad.net/ubuntu/+source/ddnet/+bug/1951680

Okay, I see the upgrade in Ubuntu devel :)
![IMG_20211124_062139.jpg](https://user-images.githubusercontent.com/51866924/143138481-6e303b4a-92be-49bf-a876-cecd86154baa.jpg)

**Comment by StarOnTheSky** [comment] 2021-11-24 10:23
Now the new release has been added to Debian testing & unstable repo.

**Closed** 2021-11-24 10:35 UTC
