### ISSUE TITLE
Editor - Reopening colorpicker sometimes decrements H value by 1.

### ISSUE THREAD

**Issue by furo321** [ddnet/ddnet#7184] opened 2023-09-15 19:46 UTC
Reported by Ssor.

https://github.com/ddnet/ddnet/assets/141338449/6661f340-6486-46ac-b47d-5262de3ce2ef

**Comment by VoxelDoesCode** [comment] 2023-09-15 19:51
Duplicate of #5844

**Closed** 2023-09-15 19:56 UTC
