### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1705] opened 2019-05-10 09:18 UTC
reported by archimede67 on discord

> yo, so when you shift click and then drag in the editor without any tile selected, the game just crashes
(version 12.3.1)

Could not reproduce it on ubuntu with current master.

**Comment by Learath2** [comment] 2019-05-10 09:27
Syltoox reported this aswell, I couldn't reproduce either.

**Comment by 12pm** [comment] 2019-05-10 09:39
Fixed by 3f76e17

**Closed by 12pm** 2019-05-10 09:39 UTC
