### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by x1len** [ddnet/ddnet#9265] opened 2024-11-19 09:45 UTC
crashes when I try to start the server, although everything is fine in the main menu, I did not touch the game files, I just installed and uploaded the library and compiled the files

**Comment by Jupeyy** [comment] 2024-11-19 09:49
Sadly the information given does not help to identify your issue.

You could add (console) logs, your operating system, the exact steps you took to install the files and start the server.

Also I think GitHub issues are not the best place to get help for beginner related things, if you can access discord, that would probably be easier.

But ofc it could still be that you encountered a bug, thus it's important to give steps to reproduce

**Comment by x1len** [comment] 2024-11-19 14:03
PS D:\SteamLibrary\steamapps\common\DDraceNetwork\ddnet> Start-Process DDNet.exe
PS D:\SteamLibrary\steamapps\common\DDraceNetwork\ddnet> 2024-11-19 14:06:08 I engine: running on windows-win64-amd64
2024-11-19 14:06:08 I engine: arch is little endian
2024-11-19 14:06:08 I engine: operating system version: Windows 10.0.19041.5072
2024-11-19 14:06:08 I storage: added path '$USERDIR' ('C:\Users\baran\AppData\Roaming/DDNet')
2024-11-19 14:06:08 I storage: added path '$DATADIR' ('data')
2024-11-19 14:06:08 I storage: added path '$CURRENTDIR' ('D:\SteamLibrary\steamapps\common\DDraceNetwork\ddnet')     
2024-11-19 14:06:08 I console: executing 'settings_ddnet.cfg'
2024-11-19 14:06:08 I client: adding 194.24.236.196:8303 to favorites
2024-11-19 14:06:08 I client: adding 26.111.208.121:8303 to favorites
2024-11-19 14:06:08 I http: libcurl version 8.8.0 (compiled = 8.8.0) 
2024-11-19 14:06:08 I sdl: SDL version 2.30.5 (compiled = 2.30.5)    
2024-11-19 14:06:08 I gfx: Created Vulkan 1.1 context.
2024-11-19 14:06:10 I gfx: GPU vendor: NVIDIA
2024-11-19 14:06:10 I gfx: GPU renderer: NVIDIA GeForce RTX 3050 Laptop GPU
2024-11-19 14:06:10 I gfx: GPU version: Vulkan 1.3.194 (driver: 512.74.0.0)
2024-11-19 14:06:10 I sound: sound init successful using audio driver 'wasapi'
2024-11-19 14:06:10 I textrender: Freetype version 2.13.2 (compiled = 2.13.2)
2024-11-19 14:06:10 I joystick: 0 joystick(s) found
2024-11-19 14:06:10 E serverbrowser: invalid address (ServerIndex=0, TypeIndex=6, AddressIndex=6)
2024-11-19 14:06:10 E serverbrowser: invalid address (ServerIndex=0, TypeIndex=8, AddressIndex=8)
2024-11-19 14:06:10 W png: warning for file "assets/emoticons/capoo_emoticons.png": iCCP: known incorrect sRGB profile
2024-11-19 14:06:10 I graphics: converted image 'xc_data/console_wallpapers/console_bg.png' to RGBA, consider making its file format RGBA
2024-11-19 14:06:10 I client: version 18.8 on win64 amd64        
2024-11-19 14:06:10 I client: git revision hash: 5638f7f13d2ef575
2024-11-19 14:06:10 I serverbrowser_http: found master, url='https://master4.ddnet.org/ddnet/15/servers.json' time=422ms age=13s
2024-11-19 14:06:11 I http: task done: https://info.ddnet.org/info?name=Animeuz
2024-11-19 14:06:11 I serverbrowser_http: found master, url='https://master1.ddnet.org/ddnet/15/servers.json' time=109ms age=2s
2024-11-19 14:06:12 I http: task done: https://info.ddnet.org/info?name=Animeuz
2024-11-19 14:06:12 I http: task done: https://master1.ddnet.org/ddnet/15/servers.json
2024-11-19 14:06:13 I client: connecting to '62.122.215.19:8322'
2024-11-19 14:06:13 I host_lookup: host='62.122.215.19' port=8322 3
2024-11-19 14:06:13 I client: connected, sending info
2024-11-19 14:06:13 I datafile: could not open 'maps/Linear.map'

**Comment by sjrc6** [comment] 2024-11-21 09:59
I get the same ``could not open`` crash seemingly randomly when using debug mode, this didn't happen before. It happens with things that aren't map files too.

**Comment by Robyt3** [comment] 2024-11-26 21:02
Closing due to lack of information and because this is not the DDNet client according to the git revision hash in the log. Please test with the latest version from https://ddnet.org/downloads/. Feel free to reopen if the issue persists with the DDNet client.

**Closed by Robyt3** 2024-11-26 21:02 UTC
