### ISSUE TITLE
Crash in anti_bot::enter_hook

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3597] opened 2021-02-03 12:52 UTC
```
Core was generated by `./DDRace64-Server_sql -f servers/8303.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fccdf84c45c in anti_bot::enter_hook (this=this@entry=0x561015b1dac0, self=self@entry=0x7fccdf85a9c0 <g_aCharacters+512>)
    at antibot.h:982
982	antibot.h: No such file or directory.
[Current thread is 1 (Thread 0x7fccdeabd200 (LWP 31366))]
(gdb) bt
#0  0x00007fccdf84c45c in anti_bot::enter_hook (this=this@entry=0x561015b1dac0, self=self@entry=0x7fccdf85a9c0 <g_aCharacters+512>)
    at antibot.h:982
#1  0x00007fccdf84a5f8 in anti_bot::on_tick (dst=0x7ffcf74610d0 "night", self=0x7fccdf85a9c0 <g_aCharacters+512>, this=0x561015b1dac0)
    at antibot.h:617
#2  AntibotOnCharacterTick (ClientID=8) at antibot_lib.cpp:234
#3  0x00005610135f640d in CCharacter::Tick (this=0x5610136eb3a0 <ms_PoolDataCCharacter+32384>)
    at /home/teeworlds/src/master/src/game/server/player.h:35
#4  CCharacter::Tick (this=0x5610136eb3a0 <ms_PoolDataCCharacter+32384>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:752
#5  0x0000561013615bfd in CGameWorld::Tick (this=this@entry=0x7fccdc4c94c0)
    at /home/teeworlds/src/master/src/game/server/gameworld.cpp:265
#6  0x000056101360a709 in CGameContext::OnTick (this=0x7fccdc4ba010) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:775
#7  0x00005610135e42ef in CServer::Run (this=0x7fccddcf0010) at /home/teeworlds/src/master/src/engine/server/server.h:110
#8  0x00005610135d05e5 in main (argc=3, argv=0x7ffcf74625f8) at /home/teeworlds/src/master/src/engine/server/server.cpp:3557
```
Happened on CHN4

**Comment by heinrich5991** [comment] 2021-02-03 12:53
@nobody-mb ^

**Comment by def-** [comment] 2021-02-03 13:14
Logs don't show anything interesting:
```
[2021-02-03 13:23:42][ddnet]: cid=1 version=15025
[2021-02-03 13:23:42][chat]: *** '千年虫csgo' entered and joined the game
[2021-02-03 13:23:42][game]: team_join player='1:千年虫csgo' team=0
[2021-02-03 13:23:42][chat-command]: 10 used /pause
[2021-02-03 13:23:42][server]: client dropped. cid=7 addr=<{183.254.101.100:7990}> reason=''
[2021-02-03 13:23:42][game]: kill killer='7:猫' victim='7:猫' weapon=-3 special=0
[2021-02-03 13:23:42][chat]: *** '猫' has left the game
[2021-02-03 13:23:42][game]: leave player='7:猫'
```

**Comment by Robyt3** [comment] 2022-10-20 20:57
Duplicate of #3028.

**Closed by Robyt3** 2022-10-20 20:57 UTC
Labels: bug, antibot
