### ISSUE TITLE
Try reenabling aio now that memory allocation is thread-safe

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1108] opened 2018-04-09 12:55 UTC
@Learath2, please test once you get back to your Windows computer.

**Comment by Learath2** [comment] 2018-10-04 13:56
Tested, still crashes instantly with aio :(

**Comment by Learath2** [comment] 2019-07-21 08:50
After an upgrade to Windows 10 this no longer happens for me. I don't think we had any other instance of it either, so I guess we can close this?

**Comment by heinrich5991** [comment] 2019-07-21 09:32
@Learath2 aio is currently not enabled on Windows. Can you check that it doesn't crash when you enable it?

**Comment by Learath2** [comment] 2019-07-21 09:37
I'm far away from my desktop, but last time we attempted enabling it, it worked fine and the aio test passes fine for a couple hundred thousand iterations.

The bug that made us disable aio was perfectly consistent, always caused a crash instantly on the first write, and crashed deep in kernel32 or ntkernel.

**Comment by Learath2** [comment] 2020-09-18 14:16
Since I no longer reproduce this and no one else seems to have encountered the same issue, maybe we should try this again?

**Comment by def-** [comment] 2020-09-25 09:28
Sounds ok to me. @heinrich5991 ?

**Comment by Robyt3** [comment] 2022-05-25 18:32
Windows uses a different logger implementation, so this issue is obsolete?

**Comment by heinrich5991** [comment] 2022-05-25 21:27
Does someone remember why we have aio at all? To not block the server? Maybe we can just disable it in the client entirely, as it makes debugging harder?

**Comment by def-** [comment] 2022-05-25 22:23
Also for client, blocking writes in same thread could be causing lags.

**Closed** 2024-01-20 17:53 UTC
Labels: enhancement, client
