### ISSUE TITLE
Feature: Restore (player)state on reload

### ISSUE THREAD

**Issue by phcrm** [ddnet/ddnet#2092] opened 2020-03-22 18:01 UTC
Currently when mapping you have to teleport all players to last position you were testing and give them the required weapons again.

Would be nice to restore (player)state on server reload. Might be a good idea to make this toggleable by a given setting (`sv_restore_on_reload 0/1`)

_Sidenote_: `sv_input_fifo` seems to require a server restart. Might be a good idea to mention [here](https://ddnet.tw/settingscommands/#server-settings).

**Comment by Learath2** [comment] 2020-03-22 19:52
Duplicate of #585

**Closed by Learath2** 2020-03-22 19:52 UTC
