### ISSUE TITLE
Server: Feature Request: Server join queue

### ISSUE THREAD

**Issue by Stepfunn** [ddnet/ddnet#8177] opened 2024-04-02 16:41 UTC
It would be really nice to have a queue to join a full server instead of retrying every 5 seconds to join.
The concept of trying every 5 seconds if there is an empty slot can stay the same, but it would be really nice to have a guarantee to join the server at some point instead of hoping for some luck.
Especially the user would have way more info on whats going on instead of just sitting in the connection screen hoping for the best.

**Comment by Robyt3** [comment] 2024-04-02 16:44
Duplicate of #3453.

**Closed by Robyt3** 2024-04-02 16:44 UTC
