### ISSUE TITLE
Move 'Show name plates' thread to the 'HUD'

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#3333] opened 2020-11-18 17:38 UTC
'Show name plates' is HUD part, imo. It isn't very comfortable to enable/disable whole HUD with tab changing.

**Comment by gerdoe-jr** [comment] 2020-11-18 17:44
'Theme' part should stay in 'Assets', not in 'General'.

**Comment by Jupeyy** [comment] 2020-11-18 19:46
I disagree on the Theme thing, it has nothing todo with assets

**Comment by C0D3D3V** [comment] 2022-06-06 15:07
I do not understand what this issue is about? 
you can just use a bind like: `bind slash "toggle cl_showhud 0 1; toggle cl_showkillmessages 0 1; toggle cl_showchat 0 1; toggle cl_nameplates 0 1"`

**Comment by Jupeyy** [comment] 2022-06-06 15:12
it's about GUI not about functionality

**Comment by C0D3D3V** [comment] 2022-06-06 15:59
Ah I see sounds plausible

**Comment by Robyt3** [comment] 2024-01-20 17:04
Duplicate of #7830.

**Closed by Robyt3** 2024-01-20 17:04 UTC
