### ISSUE TITLE
Insignificant bug: Name highlighting in chat doesn't always work right after you change name

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2190] opened 2020-05-17 21:14 UTC
I changed my name a split second before someone pinged me and it didn't highlight (neither my old name nor my new name, both of which were mentioned in the message). See attached and notice the lack of red highlighting (there was also no ping "sound").
![highlighting name is racy](https://user-images.githubusercontent.com/7715155/82160181-62bf6880-9848-11ea-8c16-8abce21ab735.png)

**Comment by ChillerDragon** [comment] 2024-09-16 04:19
I can not reproduce in the latest version. I patched the server to send a chat message in the same packet as the snapshot that sends the new name.

![image](https://github.com/user-attachments/assets/5a3bb0cf-cf80-4d9a-8277-69efca30614b)



https://github.com/user-attachments/assets/fa67df39-95bd-4b07-9ef0-566bf93cbcc3

I even built this fake packet that has a chat message after the snapshot (which in reality would never exist because snaps would flush). And then i was holding down my rename bind with no ratelimits on name changes and not a single message did not highlight.

![image](https://github.com/user-attachments/assets/57318c90-0235-48f3-8fa8-363216bf35db)

![screenshot_2024-09-16_12-13-41](https://github.com/user-attachments/assets/618ffe6b-cc08-44a6-8d9b-d934d8914d0d)

If the message only contains one name I could get it to not highlight but that seems fine.

![screenshot_2024-09-16_12-10-53](https://github.com/user-attachments/assets/da0eaa0a-ef98-43c3-a126-73ae4444f513)

**Comment by ChillerDragon** [comment] 2024-09-16 04:24
**UPDATE:** this bug has nothing todo with renames. Its the order. The code first matches d3fault within the word carriedd3fault sees that it does not start with a space and never continues to search for another hit.

the message "xfoo hi foo" would never ping a player called foo.

**Comment by Robyt3** [comment] 2024-09-17 10:17
Closed by #8963.

**Closed by Robyt3** 2024-09-17 10:17 UTC
Labels: bug, client
