### ISSUE TITLE
Import colored broadcast from 0.7

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#8039] opened 2024-03-02 07:11 UTC
We could add a SERVERCAPFLAG to let client know this server send broadcast with color,
This is a useful way for players fast know the broadcast type (e.g, database error broadcast use red color)

EDIT TITLE: Sorry my bad English

**Comment by Robyt3** [comment] 2024-03-02 09:28
Duplicate of #4897.

**Closed by Robyt3** 2024-03-02 09:28 UTC
