### ISSUE TITLE
CPU Throttle

### ISSUE THREAD

**Issue by tyurderi** [ddnet/ddnet#1422] opened 2019-01-07 08:09 UTC
Yet a similar feature is the FPS limit using `gfx_refresh_rate` but it doesn't throttle the CPU so my Laptop is getting hotter than needed.

**Comment by Jupeyy** [comment] 2019-01-07 09:51
cl_refresh_rate

**Comment by def-** [comment] 2019-01-07 10:17
The problem is that some pros notice when we limit the input reading by amount, so the default is still `cl_refresh_rate 0`

**Comment by tyurderi** [comment] 2019-01-07 12:04
cl_refresh_rate is decreasing the game performance and it feels laggy and unstable. :/

**Comment by def-** [comment] 2019-01-07 12:50
How high did you set it? Personally I use cl_refresh_rate 480 and that feels fine to me.

**Comment by tyurderi** [comment] 2019-01-07 13:17
Hmm, how is the value of cl_refresh_rate used? 

I have set it to 120 (cl_refresh_rate_inactive is also 120) and my FPS limit is also 120. But then it doesn't feel good anymore.

**Comment by def-** [comment] 2019-01-08 19:37
@Jupeyy So how about doing it the same waythat TW 0.7 is? Would that work better?

**Comment by Jupeyy** [comment] 2019-01-09 04:09
i'm not directly sure. 0.7 does alot different, but generelly that problem wouldn't exists, if the GUI simulation could be indepentend of the GUI rendering. That would be the milestone i'd go to really improve it

**Comment by def-** [comment] 2019-01-11 08:19
@Jupeyy Since you're "the graphics guy", would you mind looking into porting the TW 0.7 way to DDNet?

**Comment by Jupeyy** [comment] 2019-01-11 09:54
I'd say restructure it and reprogramm it makes more sense.
Even if i would look into it, don't expect me to do it any time soon, more like a milestone for a possible ddnet-next, that also improves other stuff:
-editor
-ping calculation
-additional packets for ddrace related stuff(being in solo etc.), instead of chat msg.

Depending on how similar 0.7 is, it might be even worth looking into dropping 0.6(ofc only if no physic changes) then, but that's totally up to, if oy will continue supporting vanilla, or gets inactive again.

**Comment by Jupeyy** [comment] 2019-01-11 10:01
if you just want to change the behaviour, i'd recommend just buffering input for the gui, and then handle it, when it's getting rendered.

**Comment by PathosEthosLogos** [comment] 2019-04-13 05:22
@Jupeyy Are you sure about setting 1000 as minimum? That doesn't make sense. Some can't even handle 300.

I would say double the refresh rate of your monitor should be good. If your monitor is 60 Hz, go `cl_refresh_rate 120`.

**Comment by Jupeyy** [comment] 2019-04-13 06:02
Yes I'm sure. If your PC can't go that high removing all limits is my suggestion. If your PC suffers by that, because cooling is too bad or something, you can look and see if there is a good trade of performance to smooth gameplay

**Comment by tyurderi** [comment] 2019-04-14 16:38
Seems fine with cl_refresh_rate 120 yet. I'll go for a long test next week.

**Comment by Jupeyy** [comment] 2019-04-14 17:35
> If feeling good, then triple or quadruple the monitor refresh rate are enough. Setting precisely double, triple, quadruple, etc. values is important. Definitely avoid prime numbers.

yes for `gfx_refresh_rate` a multiple of the refresh rate is good, but as I said in my previous posts, cl_refresh_rate has an impact on that, its bad design by the client.

**Comment by PathosEthosLogos** [comment] 2019-05-18 15:36
@tyurderi Good to close this issue?

After a bit of research, a random value like 1000 seems to be bad advice. The machine does not necessarily have to be able to handle 1000.

Always double or triple your monitor's refresh rate. This means if your monitor is 60Hz, set `gfx_refresh_rate 120`. If your monitor's refresh rate is 240 Hz, set `gfx_refresh_rate 480`.

**Comment by Jupeyy** [comment] 2019-05-18 16:46
> After a bit of research, a random value like 1000 seems to be bad advice. The machine does not necessarily have to be able to handle 1000.

i know mathematically it sounds better to have it like this. but in the end there is input handling inside the GPU code, also 120 for a 60hertz monitor musnt be better than 1000, tearing is caused by inconsistend frame timing, the more FPS the more stable by nature... the more frames, the less the chance the monitor gets a "broken" frame when rendering.. like it renders a part of the screen and then gets the new buffer and renders the rest with the new buffer... but with higher refreshrates the "next" frame more likely looks very similar.. :D

in the end only something like vsync or freesync can time it perfectly in a trade for input delay :D hope this clears it up

if we close this issue, we need a new one for:

> @def- the whole input handling is strange for sure Input()->NextFrame(); in client.cpp must be called when a gfx frame is entered, else the gui can't procced without having inputs dropped #444
0.7 does not do this btw

**Closed** 2019-05-20 06:25 UTC
Labels: client, enhancement
