### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Anarkiddy** [ddnet/ddnet#4966] opened 2022-04-09 16:15 UTC
I get kicked out of servers because of connectivity issues, but not into the menu. The game crashes via sudden blackscreen closing itself without saving any progress or reconnecting me to the server after starting the game again. Is that normal?

**Comment by Jupeyy** [comment] 2022-04-16 06:53
Since DDNet 16 on Windows there should be crash & assert logs in %appdata%/teeworlds/dumps

That would help, if you got any.

Else we need any way to reproduce it

**Comment by Anarkiddy** [comment] 2022-04-19 09:56
Thanks for the suggestion! I couldn't find any logs in the folder as it only states it's empty:
![grafik](https://user-images.githubusercontent.com/103326858/163978611-49e13625-c2b5-4edc-9d3e-936bfbae44a0.png)
How would you reproduce it?

**Comment by def-** [comment] 2022-04-19 10:03
So it seems like DDNet client closes itself without crashing. This could mean an external program is sending a termination signal to the process. Could you try closing all other applications on your system and check if this helps?

**Comment by Anarkiddy** [comment] 2022-04-19 10:46
Thank you, but I'm currently not on my device. I will update you then

**Comment by Robyt3** [comment] 2022-10-20 19:30
@Anarkiddy Any update so far?

**Comment by Robyt3** [comment] 2023-08-13 13:57
Closing due to lack of information and activity. Feel free to open another issue if you are still experiencing this issue with the latest version of the game.

**Closed by Robyt3** 2023-08-13 13:57 UTC
Labels: bug, client, to-reproduce
