### ISSUE TITLE
Editor: Random quad has random colors after moving around other quads + Crash

### ISSUE THREAD

**Issue by saltyElefant** [ddnet/ddnet#5674] opened 2022-07-29 19:47 UTC
Happend to me two times now, idk how to reproduce though, seems random.

After moving around the sun and the sunbeams, the blue background quad was randomly recolored. 
![screenshot_2022-07-29_21-01-53](https://user-images.githubusercontent.com/46008453/181832860-3cded602-f71d-4a6b-bc0d-45618591e7f0.png)

Took a screenshot, tabbed out and the client crashed afterwards.

Crashlog:
[DDNet_crash_log_quad_randomly_recolored.zip](https://github.com/ddnet/ddnet/files/9223367/DDNet_crash_log_quad_randomly_recolored.zip)

Client version: 16.2.2 released, non steam
OS win10 64bit

**Comment by def-** [comment] 2022-07-30 10:43
```
Parsing address: 1400F3695 (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/game/client/ui.h:272
Parsing address: 140109DD5 (img base: 140000000)
/usr/x86_64-w64-mingw32/include/c++/12.1.0/bits/stl_algo.h:1849
Parsing address: 14010C186 (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/game/editor/editor.cpp:3863
Parsing address: 14010CE59 (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/game/editor/editor.cpp:3980
Parsing address: 140026AE0 (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/engine/client/client.cpp:3427
Parsing address: 140219D78 (img base: 140000000)
/usr/x86_64-w64-mingw32/include/c++/12.1.0/bits/stl_bvector.h:1546
Parsing address: 1400013B1 (img base: 140000000)
/build/mingw-w64-crt/src/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323
Parsing address: 1400014C6 (img base: 140000000)
/build/mingw-w64-crt/src/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178
Parsing address: 7FFF507D7034 (img base: 140000000)
??:0
Parsing address: 7FFF51D42651 (img base: 140000000)
??:0
```

**Comment by def-** [comment] 2022-07-30 10:47
Another vulkan issue it seems, similar to #5675 :
```
Parsing address: 446954593 (img base: 140000000)
??:0
Parsing address: 140223E00 (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/engine/client/backend/vulkan/backend_vulkan.cpp:1611
Parsing address: 1401E0153 (img base: 140000000)
/usr/x86_64-w64-mingw32/include/c++/12.1.0/bits/stl_vector.h:1124
Parsing address: 140202056 (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/engine/client/backend/vulkan/backend_vulkan.cpp:6492
Parsing address: 1401DA98B (img base: 140000000)
/usr/x86_64-w64-mingw32/include/c++/12.1.0/bits/std_function.h:591
Parsing address: 140015896 (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/engine/client/backend_sdl.cpp:246
Parsing address: 140014CD3 (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/engine/client/backend_sdl.cpp:77
Parsing address: 1401A36CD (img base: 140000000)
/home/deen/isos/ddnet/ddnet-source/src/base/system.cpp:688
Parsing address: 446997034 (img base: 140000000)
??:0
Parsing address: 447E02651 (img base: 140000000)
??:0
```

**Comment by def-** [comment] 2022-07-30 11:28
Is it possible that this happened after having selected quads in one layer, then switching to another layer and selecting further quads? If so, it's a duplicate of https://github.com/ddnet/ddnet/issues/5673

**Comment by saltyElefant** [comment] 2022-07-30 11:42
Yes, I might have switched between the sun and sunbeam layer while having quads selected.

**Comment by def-** [comment] 2022-07-31 21:11
Please reopen if this still happens with https://github.com/ddnet/ddnet/pull/5678

**Closed by def-** 2022-07-31 21:11 UTC
Labels: bug, to-reproduce, editor
