### ISSUE TITLE
Autorules menu scrollbar bug

### ISSUE THREAD

**Issue by saltyElefant** [ddnet/ddnet#3192] opened 2020-10-25 19:27 UTC
Can't move it via mouse drag when it is at the most upward position.

**Comment by def-** [comment] 2020-10-25 21:00
@edg-l ^

**Comment by edg-l** [comment] 2020-10-25 22:01
I can't reproduce this, no idea tbh.

**Comment by edg-l** [comment] 2021-08-15 11:50
tell if it still happens, closing for now

**Closed by edg-l** 2021-08-15 11:50 UTC
