### ISSUE TITLE
Sixup sounds

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#2523] opened 2020-07-23 11:43 UTC
> [2:14 AM] fokkonaut: I have the feeling Sixup sounds are doubled for other players, just by looking at the code
> [2:14 AM] fokkonaut: 0.7 handles sounds for Hook attaching to players/ground/nohook clientside, for all players
> [2:15 AM] fokkonaut: so this PR should work for yourself, but if you are a 0.7 client and someone else hooks you or anybody close to you, I think you should hear 2 sounds
> [2:15 AM] fokkonaut: check out vanilla/gameclient.cpp, ProcessTriggeredEvents and where its getting called (same file)
> [2:16 AM] fokkonaut: also, 0.7 vanilla doesnt send any hook sounds to the client, this is just a guess, I cant test it right now
> [2:17 AM] fokkonaut: So we would need a NonSixupTeamMask, excluding all Sixup players for these hook sounds
> [2:22 AM] fokkonaut: https://github.com/teeworlds/teeworlds/blob/master/src/game/client/gameclient.cpp#L1094
> [2:22 AM] fokkonaut: events are only triggered for other players here:
> 
> https://github.com/teeworlds/teeworlds/blob/1846c74467e8a95a44c1ba972455e4da15083e66/src/game/client/gameclient.cpp#L1298
> [2:23 AM] fokkonaut: And here for the local character:
> https://github.com/teeworlds/teeworlds/blob/1846c74467e8a95a44c1ba972455e4da15083e66/src/game/client/gameclient.cpp#L1585
> [2:06 AM] fokkonaut: @Learath2 my guess from last night is right btw, i fixed it in my 0.7 mod:

@Fireball-Teeworlds guess that PR wasn't enough to fix it, I'm a little busy to fix this now but if you don't feel like it I'll fix it sometime next week.

**Comment by fokkonaut** [comment] 2020-07-23 12:35
https://github.com/fokkonaut/F-DDrace/commit/65777ede2143e798cd5c981bf583eb967d91d206

**Comment by Fireball-Teeworlds** [comment] 2020-07-23 12:35
@fokkonaut 

I had tested it this way:
1. Connected a vanilla 0.7 client
2. Connected a DDNet client, spawned a dummy
3. Disabled sounds in DDNet
3. Made the main DDNet tee hook the dummy
4. Heard just a single sound coming from the vanilla client

I've just tested a different case to check whether vanilla can trigger SOUND_HOOK_ATTACH_PLAYER for other players client-side:
1. I've commented out these lines for the server: https://github.com/ddnet/ddnet/blob/master/src/game/server/entities/character.cpp#L866-L867
2. I no longer hear any hook sounds from the vanilla client in the setup above

IIRC that was actually the case that led me to do the fix the way I did it.

This is interesting considering that you're right and according to the 0.7 code vanilla client should've been able to do hook sounds on it's own. It seems like there's another issue somewhere and events don't get delivered to vanilla. This is possibly the reason for the missing double jump sounds in 0.7 that I've just noticed.

**Comment by Fireball-Teeworlds** [comment] 2020-07-23 12:42
So, to summarize:
1. Hook sounds actually seem to have been fixed by that diff from a few days ago for both 0.6 and 0.7.
2. However, they are working in a different way than on a proper 0.7 server, where the server is supposed to send events instead of sounds.
3. This is possibly the reason for the missing dj sound from other players.

**Comment by fokkonaut** [comment] 2020-07-23 12:43
Ahh, maybe the triggeredevents are different between 0.6 and 0.7? Because as it looks like my fix works for my server, and appearently your fix works for ddnet (?). Sending the events here and applying my fix should be proper: https://github.com/ddnet/ddnet/blob/34b761312eb775c91eb308d51f83c27f6957f310/src/game/server/entities/character.cpp#L1205

**Comment by fokkonaut** [comment] 2020-07-23 12:43
Oh, didnt see you made a second comment that quickly :D

**Comment by Fireball-Teeworlds** [comment] 2020-07-23 12:44
Here's the commit that changed the behavior for 0.7 btw: https://github.com/teeworlds/teeworlds/commit/d2924b5ad6982945da5f2db299d964133a3e5e63. I'm going to investigate this later today.

**Comment by ChillerDragon** [comment] 2024-08-21 13:52
I can reproduce the issue by patching a teeworlds client to print when a sound is being played.

```diff
diff --git a/src/engine/client/sound.cpp b/src/engine/client/sound.cpp
index c8184b925..fca7f6c19 100644
--- a/src/engine/client/sound.cpp
+++ b/src/engine/client/sound.cpp
@@ -505,6 +505,7 @@ void CSound::SetChannelVolume(int ChannelID, float Vol)
 
 int CSound::Play(int ChannelID, CSampleHandle SampleID, int Flags, float x, float y)
 {
+       dbg_msg("sound", "playing sound %d", SampleID.Id());
        if(!SampleID.IsValid())
                return -1;
 
```

When joining a ddnet server there is only one sound being played while hooking others. But there are two sounds being played when getting hooked by others.

On vanilla teeworlds servers there is only one sound being played in both cases.


The same applies to [ground hook and player jump](https://github.com/teeworlds/teeworlds/commit/d2924b5ad6982945da5f2db299d964133a3e5e63#diff-29ffe32916052e1066eed938021aadfeb29f855d7c63d9c1ca3350aceffb79f3L621-L625).

**Closed** 2024-08-21 15:26 UTC
Labels: bug, sixup
