### ISSUE TITLE
Improve the glyph rendering engine

### ISSUE THREAD

**Issue by necropotame** [ddnet/ddnet#684] opened 2017-03-16 12:40 UTC
* The glyph cache is not packed in an efficient way (video memory waste)
* Searching the glyph position in the glyph cache use a linear search. We should use sorted_array
* freetype has already something to draw outlines, and it's probably far more optimized than the actual convolution based method
* The touch time use tile_get(), meaning that you can label as old a glyph that is rendered in the same frame. This just freeze the client in proper stress test. We should replace it by a frame counter
* Only one font can be rendered, instead of searching a glyph in a list of font (useful for CJK, or to use a monospace font for the console)

**Comment by def-** [comment] 2017-03-16 12:46
If that makes the font stop lagging for me and CJK, it would be great.

**Comment by heinrich5991** [comment] 2017-03-16 13:17
How many elements are there in the array? Linear search is faster in small arrays.

**Comment by Learath2** [comment] 2017-03-16 14:01
Lets just do it like all modern games and have the entirety of the glyphs always in vmem /s

**Comment by necropotame** [comment] 2017-03-16 14:13
@heinrich5991, just imagine a chat mixing english, arabic and russian + the leaderboard with decorations in half of player names. It can reach 200 glyph easily.

@Learath2, There is up to 20000 glyphes à CJK fonts. It's not a good solution to make them stored all the time.

**Comment by Learath2** [comment] 2017-03-16 14:25
Thus the "/s"

**Comment by def-** [comment] 2017-03-16 14:25
So how do other games solve it?

**Comment by necropotame** [comment] 2017-03-16 16:10
We certainly don't want to tessellate them to render each glyph as a polygon, so we have to deal with atlas. And since we can't put them all in the same texture, we need a dynamic cache. Then we have two choices: glyph cache or text cache. I think the second one is not suitable in our case (one reason: we redraw everything at each frame).
Last question: how to pack correctly glyph in the atlas. The actual system is horrible: the biggest glyph size is computed, an then each glyph is aligned on a grid of this size.

(Each block of a red color is a different texture)
![TeeWorlds glyph cache](https://s11.postimg.org/8mt601u0j/teeworlds_glyphcache.png)

I've made a system for TeeUniverse a bit better, where I subdivide the atlas in blocks, and where each block contains approximately glyphs with the same size. I'm sure there is better strategies, but I don't know them :(

(Each yellow block is a different texture)
![TeeUniverse glyph cache](https://s18.postimg.org/9u87hhgpl/teeworlds_text_tu_cache.png)

I will create a branch "textrendering" on which we can try to solve each problem one by one. Then I will add a benchmark so we can know what we are doing.

**Comment by Learath2** [comment] 2017-03-17 02:18
@def- turns out Unity and Unreal engine prefers to do the binpacking upfront and create a glyph atlas. There is another mode of font called dynamic where they use a skyline packed glyph cache.

@necropotame The problem is called bin packing or rectangle in rectangle packing, most of the solutions I've seen are mapped at the compile time. One trend I noticed with most of them was that they ordered glyphs from large to small.

Like always its a trade-off, if we get rid of the uniform grid we have to store the glyph size in ram. 

If we don't render an atlas for ASCII characters and keep them always loaded that also could be an improvement to consider.

It should also be no trouble to render another font and put it in an atlas aswell.

**Comment by necropotame** [comment] 2017-03-17 07:29
Thanks to provide the name of the problem :) After searching more, we are looking for a bin packing algorithm with the following constraints:
1) Online (we don't know in advance the list of rectangles)
2) Non-fixed space (the container can become bigger if we need)
3) No removal of item, since we will replace the old ones (this maybe implies that we somehow round the size of a glyph)

I like this one http://blackpawn.com/texts/lightmaps/ but we have to redo the entire tree each time the atlas is full and need a resize. Or we can create a pagination system where each page is a mini tree.

Btw, improve the cache is maybe the last thing to do. We should first try to improve simple parts and see :)

**Comment by Learath2** [comment] 2017-03-17 11:01
We should probably measure the amount of vmem we are wasting before bothering to pack it any tighter.

**Comment by eeeee** [comment] 2017-07-17 17:40
There's this library https://github.com/rougier/freetype-gl , apparently it packs the glyphs really tightly: 
![freetypeglatlas](https://user-images.githubusercontent.com/681047/28281516-3e292e26-6adc-11e7-8c4f-1a400212fcb6.png)

Not sure if it's any good for CJK though, might have similar issues.

**Comment by def-** [comment] 2017-07-17 17:47
For a start it would be great if we could render glyphs async, so that the game doesn't hang, but instead the text is just delayed a bit.

**Comment by PathosEthosLogos** [comment] 2018-02-17 04:06
Probably related to #809

**Comment by Learath2** [comment] 2019-07-21 08:44
@Jupeyy does your rework on the text rendering address these?

**Comment by Jupeyy** [comment] 2019-07-21 08:48
yeah should be fixed with the rework

**Closed** 2019-07-21 09:06 UTC
Labels: client
