### ISSUE TITLE
/showall 1 and go in spec, hear people double jumping from every distance

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1532] opened 2019-03-22 06:03 UTC
As reported by Jesus Christ on discord.

Might be caused by https://github.com/ddnet/ddnet/commit/a7548511bff2b88ed06014fefd7217f8e1b78cc0

**Comment by def-** [comment] 2019-03-25 17:59
Can't reproduce, tried with Wine and Linux. Anyone who can reproduce it can tell me what's printing when sound is init?

Mine is
```
[2019-03-25 18:57:51][client/sound]: sound init successful using audio driver 'wasapi'
```

**Comment by daverck** [comment] 2019-03-29 13:26
Can't reproduce on windows 10 pro.
Maybe it's related to the map ?

**Comment by Jupeyy** [comment] 2022-05-28 06:32
This was probably caused by the bug that was fixed in #4830

If we get new reports we can also create a new issue

**Closed by Jupeyy** 2022-05-28 06:32 UTC
Labels: bug, client, toreproduce
