### ISSUE TITLE
Coloured console text

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1167] opened 2018-06-23 01:50 UTC
From a reply in #1061 

It would be really nice if this is applied! Distinguishing team colours, server message, etc. would be really helpful.

**Comment by Learath2** [comment] 2018-06-23 01:53
Console text as in F1 or the actual stdout?

**Comment by PathosEthosLogos** [comment] 2018-06-23 01:56
I was thinking F1, but both would be nice actually. I think stdout isn't really necessary for colour though, because nobody really uses it.

**Comment by def-** [comment] 2018-09-11 12:52
Duplicate of #610

**Closed by def-** 2018-09-11 12:52 UTC
