### ISSUE TITLE
UI walkthrough for new players

### ISSUE THREAD

**Issue by kaitlynia** [ddnet/ddnet#8094] opened 2024-03-12 02:16 UTC
Some games that have complicated UIs give the player a walkthrough of how to use it. My idea at first was to put this in the tutorial, prompting the player to press Escape and Kill to retry, but since it can't be localized properly and don't really need to change the map, I think it should be separate before you start the tutorial. It would need to teach the player how to press Escape to reach those options, and also explain some of the inner options that are most common, like antiping, changing your tee's appearance, display resolution, and controls. Scope is hard to establish here because we may not all agree on what is considered common options, but at the very least teaching the player how to access these menus is a good start.

**Comment by Robyt3** [comment] 2024-03-13 20:34
Duplicate of #2583.

**Closed by Robyt3** 2024-03-13 20:34 UTC
