### ISSUE TITLE
Crash in RenderServerbrowserServerList while typing in search

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3370] opened 2020-11-30 10:19 UTC
```
(gdb) bt
#0  0x00007f075edcd36d in __strncpy_avx2 () at /usr/lib/libc.so.6
#1  0x0000556fa5b40e13 in strncpy (__len=63, __src=<optimized out>, __dest=<optimized out>)
    at /usr/include/bits/string_fortified.h:106
#2  str_copy (dst=<optimized out>, src=<optimized out>, dst_size=dst_size@entry=64) at src/base/system.c:2345
#3  0x0000556fa5bd6b16 in CMenus::RenderServerbrowserServerList(CUIRect) (this=0x556fa5dc34e0 <gs_Menus>, View=...)
    at src/game/client/components/menus_browser.cpp:185
#4  0x0000556fa5bd9ae4 in CMenus::RenderServerbrowser(CUIRect)
    (this=this@entry=0x556fa5dc34e0 <gs_Menus>, MainView=...) at src/game/client/components/menus_browser.cpp:1339
#5  0x0000556fa5bcdcaf in CMenus::Render() (this=this@entry=0x556fa5dc34e0 <gs_Menus>)
    at src/game/client/components/menus.cpp:1289
#6  0x0000556fa5bd115a in CMenus::OnRender() (this=0x556fa5dc34e0 <gs_Menus>)
    at src/game/client/components/menus.cpp:2396
#7  0x0000556fa5c14707 in CGameClient::OnRender() (this=0x556fa5d5f3c0 <g_GameClient>)
    at src/game/client/gameclient.cpp:676
#8  0x0000556fa5b66e85 in CClient::Render() (this=0x7f075dc26010) at src/engine/client/client.cpp:1134
#9  0x0000556fa5b6f508 in CClient::Run() (this=this@entry=0x7f075dc26010) at src/engine/client/client.cpp:3290
#10 0x0000556fa5afdaaf in main(int, char const**) (argc=3, argv=0x7fff24b31538) at src/engine/client/client.cpp:4356
```
Can't reproduce. Was in RelWithDebInfo build.

**Comment by Jupeyy** [comment] 2022-03-13 10:56
Closing for now, since not reproducable and server browser was reworked

**Closed by Jupeyy** 2022-03-13 10:56 UTC
