### ISSUE TITLE
Crash in PurgeUntil with > 60 players on server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3903] opened 2021-06-13 09:10 UTC
Reported by Quick from DDPER:
```
Thread 1 "DDNet-Server" received signal SIGABRT, Aborted.
0x00007ffff74c27bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff74c27bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff74ad535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7504508 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff750ac1a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff750c8a2 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x000055555564cb2e in CSnapshotStorage::PurgeUntil (this=0x7ffff66b64e0, Tick=58502)
    at /home/ddnet/src/engine/shared/snapshot.cpp:459
#6  0x0000555555571d91 in CServer::DoSnapshot (this=0x7ffff66b6010)
    at /home/ddnet/src/engine/server/server.cpp:892
#7  0x000055555557a29c in CServer::Run (this=0x7ffff66b6010)
    at /home/ddnet/src/engine/server/server.cpp:2613
#8  0x000055555557fe92 in main (argc=1, argv=0x7fffffffebe8)
    at /home/ddnet/src/engine/server/server.cpp:3613
(gdb)
```
I can't reproduce it, we regularly have > 60 players on official DDNet servers. I'm guessing some undefined behaviour is being handled differently in another compiler/platform.

**Comment by ChillerDragon** [comment] 2021-08-14 13:44
Was this crash created with unmodified ddnet or with some ddper fork?

**Comment by Jupeyy** [comment] 2022-03-13 11:10
Closing, since not reproducable and too few information on if DDPER uses custom code

Also we had alot of snapshot fixes lately

Also its a potential dublicate of #2677

**Closed by Jupeyy** 2022-03-13 11:10 UTC
Labels: bug, server, toreproduce
