### ISSUE TITLE
Hookstop tile acts like hookthrough?

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1737] opened 2019-05-18 18:10 UTC
![Screen 1839](https://user-images.githubusercontent.com/47721445/57973355-fea16480-79a7-11e9-981f-4b64d4b0eeb9.png)
Why does this tile act as hookthrough?
Noticed just now while playing Grandma.
![Screen 1840](https://user-images.githubusercontent.com/47721445/57973405-c9e1dd00-79a8-11e9-8fe4-082b47d8ad79.png)
(it has the same texture as new hookthrough tile, i'm guessing the mapper mistook hookstop for hookthrough)

**Comment by 12pm** [comment] 2019-05-18 18:13
that's by design

**Comment by VxMiMxV** [comment] 2019-05-18 18:17
neato

**Comment by fokkonaut** [comment] 2019-05-30 15:41
close

**Comment by VxMiMxV** [comment] 2019-05-31 00:50
I actually didn't get an answer though.

**Comment by Ryozuki** [comment] 2019-05-31 07:24
> 
> 
> I actually didn't get an answer though.

If u are using new versions of ddnet, go to editor, hover over the tile, and u get a description on bottom.

Now, close this.

**Comment by fokkonaut** [comment] 2019-05-31 10:38
You got, its by design. This is an intended feature

**Comment by VxMiMxV** [comment] 2019-06-01 19:31
Why does this tile act as hookthrough?
-Because it's a feature.
neato

**Closed** 2019-06-01 19:45 UTC
