### ISSUE TITLE
teleport prediction

### ISSUE THREAD

**Issue by AssassinTee** [ddnet/ddnet#6549] opened 2023-04-30 20:47 UTC
I tested the game with a higher prediction margin, e.g. cl_prediction_margin 2000 and noticed that tps seem not to be predicted at all, not even rudimentary.
![screenshot_2023-04-30_22-45-21](https://user-images.githubusercontent.com/821401/235375512-74abd2fa-948c-4e46-bc06-c82aa83ababa.png)

Also I noticed, that selfkills and respawns are not working properly, you look like you respawn somewhere else than the respawn point

**Comment by VoxelDoesCode** [comment] 2023-04-30 20:55
This actually ties back to #237, if you want to have a look at that.

**Comment by Robyt3** [comment] 2023-07-02 11:30
Duplicate of #237.

**Closed by Robyt3** 2023-07-02 11:30 UTC
