### ISSUE TITLE
Bug: Numerous skin resolution warnings appear when selecting servers in the server browser

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#7829] opened 2024-01-19 10:13 UTC
Windows 11, 64Bit
Steam, Nightly build

![DDNet_NY0JyYA2gH](https://github.com/ddnet/ddnet/assets/60477660/99d1c475-22df-4f2a-8cbd-f3622a934216)

I couldn't bisect the first bad commit due to the following unrelated error's:

Commit: bcf86d81

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2679	binary '=': no operator found which takes a right-hand operand of type 'int' (or there is no acceptable conversion)	engine-shared	C:\Users\-----------\GitHub\ddnet\src\engine\shared\http.cpp	418	
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'C:\Users\-----------\GitHub\ddnet\out\build\engine-shared.dir\Debug\http.obj'	game-client	C:\Users\-----------\GitHub\ddnet\out\build\LINK	1	
```

**Comment by heinrich5991** [comment] 2024-01-19 11:20
Duplicate of #7829, I think.

**Comment by heinrich5991** [comment] 2024-01-19 11:20
> I couldn't bisect the first bad commit due to the following unrelated error's:

You can use `git bisect skip` for commits that don't compile.

**Closed by heinrich5991** 2024-01-19 11:20 UTC

**Comment by murpii** [comment] 2024-01-19 11:25
> Duplicate of #7829, I think.

You referenced the wrong issue I think. :D

**Comment by heinrich5991** [comment] 2024-01-19 11:27
Duplicate of #7818.
