### ISSUE TITLE
Segmentation fault when entering a game

### ISSUE THREAD

**Issue by Tardo** [ddnet/ddnet#7652] opened 2023-12-14 17:12 UTC
Since last update i get a segmentation fault:

```
2023-12-14 18:03:50 I client: connecting to '176.9.114.238:8320'
2023-12-14 18:03:50 I host_lookup: host='176.9.114.238' port=8320 3
2023-12-14 18:03:50 I client: connected, sending info
2023-12-14 18:03:50 I datafile: could not open 'maps/Patchwork.map'
2023-12-14 18:03:50 I motd: DDraceNetwork - ddnet.org
2023-12-14 18:03:50 I motd:            Moderate Server
2023-12-14 18:03:50 I motd: 
2023-12-14 18:03:50 I motd: ╭─           Cᴜʀʀᴇɴᴛ Mᴀᴘ
2023-12-14 18:03:50 I motd: │ Map: Patchwork
2023-12-14 18:03:50 I motd: │ Mapper: Cøke, Tridemy & Qywinc
2023-12-14 18:03:50 I motd: │ Difficulty: ★★★★★ (15 Points)
2023-12-14 18:03:50 I motd: │ Released on 2020-07-11
2023-12-14 18:03:50 I motd: │ 3834 finishes by 3365 tees
2023-12-14 18:03:50 I motd: │ Top Time: 37:16
2023-12-14 18:03:50 I motd: │ Median Time: 04:12:24
2023-12-14 18:03:50 I motd: │ Worst Time: 57:38:36
2023-12-14 18:03:50 I motd: ╰───────────────────────
2023-12-14 18:03:51 I tune: tune_zone 1 shotgun_strength -15
2023-12-14 18:03:51 I chatresp: No such command: tune_zone_enter.
2023-12-14 18:03:51 I chatresp: No such command: switch_open.
2023-12-14 18:03:51 I chatresp: No such command: switch_open.
2023-12-14 18:03:51 I chatresp: No such command: switch_open.
2023-12-14 18:03:51 I chat: *** 'Eʟ Levii' has left the game
2023-12-14 18:03:51 I chat: *** '(1)unsigned cha' entered and joined the game
2023-12-14 18:03:51 I chat: *** DDraceNetwork Mod. Version: 0.6.4, 17.4
2023-12-14 18:03:51 I chat: *** please visit DDNet.org or say /info and make sure to read our /rules
2023-12-14 18:03:51 I chat: *** Welcome to DDraceNetwork!
2023-12-14 18:03:51 I demo_recorder: Recording to 'demos/auto/Patchwork_2023-12-14_18-03-51.demo'
2023-12-14 18:03:51 I demo_recorder: Recording to 'demos/auto/race/Patchwork_tmp_223969.demo'
2023-12-14 18:03:51 I client: got pong from current server, latency=43ms
[1]    223969 segmentation fault (core dumped)  ./DDNet
```

DDNet 17.4 / Manjaro KDE

**Comment by ChillerDragon** [comment] 2023-12-14 17:17
What is your libcurl version?

**Comment by Tardo** [comment] 2023-12-14 17:23
> What is your libcurl version?

8.5.0-1

**Comment by Jupeyy** [comment] 2023-12-14 17:32
Thanks for reporting, this is a duplicate of #7636.

Since it's already reported i'll close this issue. If you have further question you can ofc comment there.

A quick workaround is downgrading curl

**Closed by Jupeyy** 2023-12-14 17:32 UTC
