### ISSUE TITLE
Add verify_url to recognized master server server entries

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#6808] opened 2023-07-04 19:16 UTC
This url can then be used by the client to verify yourself, e.g making a curl request or opening it in the browser. We can also show a hover tooltip for clueless tees

this is related to the ger10.ddnet.tw thing

**Comment by heinrich5991** [comment] 2023-07-04 20:50
I agree that some automatic verification would be nice.

The main problem I've seen so far is that I don't know how to integrate it with the connect strings we currently have. Optimally, the connect string can represent this, so that you can also connect to the server if it's not in the server list. I couldn't come up with a good syntax for that yet.

**Comment by def-** [comment] 2024-09-06 13:56
Duplicate of https://github.com/ddnet/ddnet/issues/8210 (which is newer, but has discussion)

**Closed by def-** 2024-09-06 13:56 UTC
Labels: server, client, needs-discussion
