### ISSUE TITLE
Add new net message for message box

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#8165] opened 2024-03-29 13:03 UTC
This is a great change for the mods like MRPG0.6,

The servers could send message to get client input, e.g. password, username.
```
NetMessageEx("Sv_MessageBox", "send-message-box@netmsg.ddnet.org", [
		NetIntAny("m_Flags"),
		NetString("m_pMessage"),
	]),
NetMessageEx("Cl_MessageBoxInput", "input-message-box@netmsg.ddnet.org", [
		NetString("m_pInput")
	])

# Flags
MessageBoxFlags = ["YES_NO", "TEXT_INPUT"]
```

**Comment by Bamcane** [comment] 2024-03-29 13:05
Also, we could send it to send like a motd but no need to resend the server motd

**Comment by Robyt3** [comment] 2024-03-29 14:37
Seems like a duplicate of #2875, although allowing text or other input hasn't been explicity proposed in that issue.

**Comment by Bamcane** [comment] 2024-03-30 02:33
> Seems like a duplicate of #2875, although allowing text or other input hasn't been explicity proposed in that issue.
> 
> 看起来像是#2875的副本，尽管在那个问题中没有明确提出允许文本或其他输入。

#2875 seemed like custom Net GUI, but this issue is just create a box like this:

**Comment by Bamcane** [comment] 2024-03-30 02:36
Now, i'm tried to let player reconnect many times to open message boxes, but it's too hard to do multiple languages

**Comment by Robyt3** [comment] 2024-03-30 09:37
The proposal in #2875 is about "interactive" help, so I think text inputs could also be included in that issue instead of tracking it separately.

**Comment by Robyt3** [comment] 2024-07-04 15:53
I'll consider this duplicate of #2875. We should discuss on that issue which use cases we want to support. Supporting interactive text input definitely seems useful.

**Closed by Robyt3** 2024-07-04 15:53 UTC
