### ISSUE TITLE
player moves on dummy connect

### ISSUE THREAD

**Issue by timgame** [ddnet/ddnet#174] opened 2015-03-21 06:34 UTC
sometimes when i connect my dummy after doing the solopart with my player, when i arrieve at the startline with my player, my dummy is waking right and hammering. its annyoing because he passes the startline and i cant join team anymore. I guess he is also jumping and hooking but you know what happens if you hold jump or hook. Switching to the dummy fixed the problem immediatly.

**Comment by def-** [comment] 2015-03-21 08:14
Somehow something isn't initialized, but I'm not sure what, because this doesn't seem to happen for me.

**Comment by imcaffrey** [comment] 2015-03-25 13:32
It happens to me ,either.
---
Sadly when I control the dummy to hook and then switch,the dummy keeps hooking.
It sounds right here,but when it comes to me moving left,and I switched...
I hoped it to stop,but the dummy didn't. Guess what happened...the dummy went straight int the freezing zone..
---
Sorry for my poor English,wish DDNet to become better!

**Comment by def-** [comment] 2015-03-25 13:46
That's another issue, @imcaffrey. That is intentional, but you can disable it with `F1`, `cl_dummy_resetonswitch 1`.

**Comment by imcaffrey** [comment] 2015-03-27 12:29
thanks @def- 
By the way,how can I know that what else I can do with F1?

**Comment by timgame** [comment] 2015-03-27 12:52
http://ddnet.tw/settingscommands/#client-settings
http://ddnet.tw/settingscommands/#client-commands

**Comment by def-** [comment] 2015-04-19 12:07
Hopefully fixed in https://github.com/def-/ddnet/commit/9c1e65a1f570f8278c9ab6b0ab1c3aa8949b790c

**Comment by east** [comment] 2015-11-09 05:57
Apparently not fixed.
http://forum.ddnet.tw/viewtopic.php?t=2686&p=29018

But I can't reproduce it either.

**Comment by imcaffrey** [comment] 2015-11-09 06:43
@east Things happen to me.

//But what I mentioned on Mar 25 has nothing to do with this.

**Comment by H-M-H** [comment] 2015-11-09 18:53
I can reproduce (just connected and disconnected dummy several times). I will try to fix this soon. Already had a look at dummy code and well I guess some major cleanup would be nice, let's see if I find the time to do so.

**Closed** 2015-11-11 19:53 UTC
