### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#7754] opened 2024-01-03 16:08 UTC
![Error scanning demo file](https://github.com/ddnet/ddnet/assets/366230/5137acc5-e0ba-49a5-8e15-846fed149d83)

[Looney_45.860_Breathess.demo.zip](https://github.com/ddnet/ddnet/files/13821044/Looney_45.860_Breathess.demo.zip)

Comes from here:

https://github.com/ddnet/ddnet/blob/022cae6f20bdf9d997238906c056de953197f662/src/engine/shared/demo.cpp#L776-L781

https://github.com/ddnet/ddnet/blob/022cae6f20bdf9d997238906c056de953197f662/src/engine/shared/demo.cpp#L522-L526

https://github.com/ddnet/ddnet/blob/022cae6f20bdf9d997238906c056de953197f662/src/engine/shared/demo.cpp#L470-L471

`NewTick` is -1524740773, looks like a random number to me.

Discarding this check and still playing the demo works. It shows a huge total time (8589:27:22) in the player, but the metadata seems correct (00:49). Seeking within that works, after the demo finishes or when seeking past 00:49, I get "Error during network decompression".

**Comment by Robyt3** [comment] 2024-01-03 18:11
See #7349. Just so we are on the same page, do you prefer that we do best effort playback of demos instead of doing strict validation (and accepting bugs like huge total time and skipping with the mouse not working)?

We could consider the demo to end with success (`CHUNKHEADER_EOF`) when encountering these ticks instead of ending with failure (`CHUNKHEADER_ERROR`) which would at least fix the issue of the seek bar going to the left into the negative with some broken demos.

I'm working on recording demos to temporary files first, which should hopefully prevent some of the broken demos from being recorded in the first place.

**Comment by heinrich5991** [comment] 2024-01-03 18:20
> strict validation (and accepting bugs like huge total time and skipping with the mouse not working)?

I prefer strict validation.

> I'm working on recording demos to temporary files first, which should hopefully prevent some of the broken demos from being recorded in the first place.

Yea, I mostly opened this issue so we can find out how this incorrectly formatted demo got reccorded. Is this a duplicate of #7349? Feel free to close it then.

**Comment by Robyt3** [comment] 2024-01-03 21:39
Duplicate of #7349.

**Closed by Robyt3** 2024-01-03 21:39 UTC
