### ISSUE TITLE
Nightly: crash on dummy connect

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1657] opened 2019-04-22 02:01 UTC
As soon as "connect dummy" is clicked, it:

1) goes to server list menu

2) crash immediately

**Comment by def-** [comment] 2019-04-22 07:45
Only nightly or also 12.2?

**Comment by trml** [comment] 2019-04-22 08:37
Does it happen on any type of server?

**Comment by def-** [comment] 2019-04-24 16:03
Happens all the time? Might be a duplicate of https://github.com/ddnet/ddnet/issues/1415

**Comment by FallenKN** [comment] 2019-08-01 22:02
latest master crashes when connecting a dummy on 0.6.5 under windows, maybe that was it?

**Comment by Learath2** [comment] 2019-08-05 16:38
#1698 for that issue @FallenKN

**Comment by Learath2** [comment] 2019-10-13 15:21
@PathosEthosLogos Still a thing?

**Closed** 2020-06-23 15:14 UTC
Labels: bug, client, toreproduce
