### ISSUE TITLE
Suggestion: The exclude filter shouldn't affect the friends list

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#8878] opened 2024-09-02 11:29 UTC
It would be nice if the exclude filter doesn't impact the friends list, allowing me to see which of my friends is currently online, regardless of whether their server is excluded by the filter or not.

**Comment by furo321** [comment] 2024-09-02 14:49
Duplicate of #8523

**Closed** 2024-09-03 09:14 UTC
