### ISSUE TITLE
hookcollcolour is not working correctly when in solopart and watch other people using it

### ISSUE THREAD

**Issue by Zoozti** [ddnet/ddnet#1594] opened 2019-04-07 14:30 UTC
When you are in a solopart and watch people play, their hookcoll is not getting yellow if they aim at a tee. Even when you are in spectator mode. You have to unsolo first to see it working correctly and it works also for spectator mode then.
Should not be too hard to fix i guess?

**Comment by def-** [comment] 2019-04-07 16:02
Duplicate of https://github.com/ddnet/ddnet/issues/258

**Closed by def-** 2019-04-07 16:02 UTC
