### ISSUE TITLE
Open News tab automatically, if you press the green news icon

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3428] opened 2020-12-20 17:53 UTC
I chatted with a couple of people who were unaware that there's a tournament today. I think it would be better if we switched to the news tab if there are new entries.

**Comment by def-** [comment] 2020-12-20 17:56
We used to do that and it was not so popular.

**Comment by Learath2** [comment] 2021-01-11 17:45
With who though. There are people against every ui change we ever try. 

It sounds reasonable to show news to people, especially the steam people who don't engage with the community in the other ways

**Comment by def-** [comment] 2021-01-11 17:56
For the Steam players we have news inside of Steam already, so I'd argue that we shouldn't show the in-client news at all.

**Comment by l-ouis** [comment] 2021-01-11 18:08
A lot of people using steam can easily miss the Steam news, for example whenever I launch DDNet I just use the app icon in the bottom right which skips over any announcements. I think the green highlight in the main menu is enough to get people to recognize there's new news.

**Comment by Robyt3** [comment] 2022-06-13 21:07
> Speaking about the green icon. I just tried it. If you click it, you open the main menu, but not the news page.

Isn't that intended? The green icon is normally the home button that always returns to the start menu. The green just means there are news, but it still works like the home button. I suppose it's useful for players that skip the start menu, as they would otherwise not see the green news button in the start menu.

**Comment by def-** [comment] 2022-06-13 22:09
Yes, works as intended. People were annoyed by news tab being opened automatically, so we don't do that anymore.

**Comment by C0D3D3V** [comment] 2022-06-13 22:19
So do we want to close this. Or do we want a more agressive popup for only tournaments but not for any other news.

**Comment by def-** [comment] 2022-06-13 22:36
Imo close. For tournaments we have server broadcasts too, Steam announcements etc.

**Closed** 2022-06-16 08:39 UTC
Labels: bug
