### ISSUE TITLE
Android ingame controls discussion

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8359] opened 2024-05-12 11:16 UTC
Please discuss how the ingame controls for Android could look and work like in this issue first.

Technical requirements:

- Android controls should be a separate gameclient component and require minimal changes to the rest of the client.

**Comment by heinrich5991** [comment] 2024-05-12 20:30
Do we know other games that port a traditional keyboard/controller played game to Android?

I guess emulators do that. They show on-screen controllers, I think.

**Comment by Jupeyy** [comment] 2024-05-20 09:45
Could we send SDL events for controllers to reuse the controller logic? Or is that more complicated than handling it in our logic directly.

Do you already checked for multi-touch stuff? I guess it now needs a device id for pointer/cursor events.


Then the component could be pretty slim i guess, since it only listens for multi-touch events and renders some circles

**Comment by Robyt3** [comment] 2024-05-20 10:13
> Could we send SDL events for controllers to reuse the controller logic? Or is that more complicated than handling it in our logic directly.

Probably easier to do it separately from the controller logic.

> Do you already checked for multi-touch stuff? I guess it now needs a device id for pointer/cursor events.

Yeah, the new component would need to handle the touch and maybe also multi-gesture events specifically instead of using the normal mouse-related events. I would keep the mouse system separate, so it should be possible to use mouse and touch separately at the same time, since both are different events.

This is the information we can get from the SDL events:

```cpp
typedef struct SDL_TouchFingerEvent
{
    Uint32 type;        /**< SDL_FINGERMOTION or SDL_FINGERDOWN or SDL_FINGERUP */
    Uint32 timestamp;   /**< In milliseconds, populated using SDL_GetTicks() */
    SDL_TouchID touchId; /**< The touch device id */
    SDL_FingerID fingerId;
    float x;            /**< Normalized in the range 0...1 */
    float y;            /**< Normalized in the range 0...1 */
    float dx;           /**< Normalized in the range -1...1 */
    float dy;           /**< Normalized in the range -1...1 */
    float pressure;     /**< Normalized in the range 0...1 */
    Uint32 windowID;    /**< The window underneath the finger, if any */
} SDL_TouchFingerEvent;

/**
 * Multiple Finger Gesture Event (event.mgesture.*)
 */
typedef struct SDL_MultiGestureEvent
{
    Uint32 type;        /**< SDL_MULTIGESTURE */
    Uint32 timestamp;   /**< In milliseconds, populated using SDL_GetTicks() */
    SDL_TouchID touchId; /**< The touch device id */
    float dTheta;
    float dDist;
    float x;
    float y;
    Uint16 numFingers;
    Uint16 padding;
} SDL_MultiGestureEvent;
```

https://github.com/libsdl-org/SDL/blob/a26d2e705d3e5c4ad1880b228b908cd3a2b9236b/include/SDL_events.h#L519-L551

So we should be able to differentiate the touch events of two different fingers.

Though we have to consider that the exact information available depends on the devices' touch screen driver. For example the pressure value for touch events can have very different values/ranges depending on the driver. For the UI, I would try to make it possible to move the mouse without clicking when the pressure value is low and only cause a UI click for higher pressure.

> Then the component could be pretty slim i guess, since it only listens for multi-touch events and renders some circles.

Yeah, the component has to render the touch controls, handle touch events and feed the inputs into `CControls` or the client directly.

My basic ideas for the touch controls would be:

- one virtual joystick on the left side for moving left and right and for jumping
- alternatively a button in the middle for jumping
- one virtual joystick on the right side for aiming
- two buttons on the right side for fire and hook
- maybe pressure-based usage of fire/hook with the virtual joystick

**Comment by heinrich5991** [comment] 2024-05-22 11:45
> For the UI, I would try to make it possible to move the mouse without clicking when the pressure value is low and only cause a UI click for higher pressure.

Is that pressure thing commonly available? Also, taking a step back, is there a point in displaying a mouse cursor on Android?

> * one virtual joystick on the right side for aiming

Would it be feasible to simply touch where you want to hook/shoot?

**Comment by Robyt3** [comment] 2024-05-22 16:27
> Is that pressure thing commonly available?

Apparently not (sample size of 1 phone :/ ), so we'll probably scratch that idea. The touch position, pressure and size values can be tested by enabling the _Pointer location_ debugging tool in the Developer options.

> Also, taking a step back, is there a point in displaying a mouse cursor on Android?

I guess not. I'm just not sure yet how much work it is to add "true" absolute touch support for the UI instead of trying to emulate a laptop trackpad with relative touch support. Using relative touch has some unfixable issues (cursor will be stuck on draggable UI elements and elements that lock the mouse position) if we can't use pressure values, so we probably have to go for absolute touch input for the UI in any case. I would not show the cursor if touch input is used or only show it briefly after the touch event. Mouse input would be completely separate from touch input, so you could still connect a mouse to the Android device and use that normally (which should show a cursor).

> Would it be feasible to simply touch where you want to hook/shoot?

That would also be possible and probably the most intuitive to use on a touch device.

A potential issue with this, in particular on devices with small screens, could be that touching and holding where you want to hook might block the relevant part of the screen from your view.

Also several more questions: How to hook/shoot? One action can be performed by the normal touch. The other action would need a separate button. Should default touching use hook or fire? How would you aim before using the hook with absolute touch input? With a joystick you would first move the joystick to the desired direction and then press the hook button, but with absolute touch input I suppose you would either have to hold the hook button down first like a modifier or always position the cursor by first shooting.

**Comment by heinrich5991** [comment] 2024-05-22 16:40
> > Is that pressure thing commonly available?
> 
> Apparently not (sample size of 1 phone :/ ), so we'll probably scratch that idea. The touch position, pressure and size values can be tested by enabling the _Pointer location_ debugging tool in the Developer options.

Ah. On my phone it seems to be available.

> Also several more questions: How to hook/shoot? One action can be performed by the normal touch. The other action would need a separate button.

Perhaps a toggle button for what the first touch does. The second touch while hooking could shoot.

**Comment by Jupeyy** [comment] 2024-06-19 08:44
I talked to ForgottenCat on discord, who is a mobile player pro that can even finish insane maps (shameless ad: https://www.youtube.com/channel/UC7iSXwN4fZCN5h2hwOQjukA).

ForgottenCat suggested some things, I guess we should break them down and see what we do anyway and what we should respect additionally:

1. About movements like +left,+right ,+jump, dont place them into one joystick,like the current android version.Because we jump while running will be  very hard.
You may place +right and +left into one joystick, but leave +jump alone.

2. About the hook.As you know the current version,we touch the joystick2, it will aim and hook at the same time. The problem is : we cant hook without the joystick2, even if I tried to bind other buttons. None of them is useful. For example, bind a "+hook",and touch the button a,nothing happened,even if I turn off the joystick2.
Using the joystick2 to aim is a wonderful idea, but I hope the joystick2 can also be remapped.For example, I remap joystick2 to the button c. When I touch the joystick2,  it aim and trigger the button c at the same time.

3. The button bug.This is a very serious bug.
When I hold the hook joystick, such as some endless hook part, it will randomly release.(I didn't release at all). And some time it doesn't release, including every button on the screen. For example, Polarity. Sometimes the hook doesn't release, causing lots of failure.
Another bug is, when some special area on the screen is touched together, all the button will die. You cant trigger them again unless you release all the finger on the screen. This bug was found when I tried to kick tees. Usually pressing hook, then +right, then +jump within a small period of time. And all keys died. But then I moved the jump button up a little, this bug doesn't exist.
**(Jupeyy: I guess these bug won't exist in the way they existed in the old version, simply bcs we do it differently :D)**

4. The entity bug.
When I am in ddnet, whether in a server or not, if I put ddnet in the background of the phone(I dont know how to describe,  just touch the menu button of the phone, or power button), when I reopen the ddnet client, all entity will turn to completely white.If you do this for several times, all tiles, editor, skins, everything will be bugged.
**(Jupeyy: This should be fixed, android destroys the surface of the app while in background, the old version then tried to recreate all graphics at runtime, which didnt really work out in all cases. Our current version should instead simply leave all VRAM as is and just create/destroy the surface using SDL window destroy/create events)**

5. The zoom bug.
If you zoom out too much, the system of the phone will break down.
Now the bug is finished, let's talk about how I bind.Maybe helpful to you.
**(Jupeyy: Yeah old android version uses OpenGL 1.x, we all know the zoom laggs. If the android they use supports GLES 3 or vulkan it should be fine)**

6. Not enough buttons:
As you know ,the buttons on phone client is not enough at all, 7 on screen ,4 two-finger gestures button, 3 physical keys(volume+,-,and back).
I use a special method called mode button,  I remap the volume+ to RCTRL, the volume- to LALT.
The old client doesn't support binds like bind ctrl+a "".
As a workaround ForgottenCat used the exec cfg logic to rebind stuff on the fly.
**(Jupeyy: I guess what ForgottenCat wants is some kind of extra overlay with lot more buttons to press, but less regulary? @Robyt3 You also have a hamburger menu.. Can we put extra buttons there?)**

7. Chat makes the client lag and is too annoying.
Since ForgottenCat used echo in the cfg files that are executed, there was a lot of echo spam and this was annoying (took too much screen space) and additionally made the client lag.
**(Jupeyy: i guess the lag is not as important :D, should be fixed)**

8. Some bugs that are probably related to the client being old:
Free-view spec didnt work, zoom didnt work on KoG

**Comment by Robyt3** [comment] 2024-06-19 16:33
Screenshot of the current draft for reference, the texts are placeholders: ![screenshot_2024-06-18_18-38-21](https://github.com/ddnet/ddnet/assets/23437060/34682bc1-5ec1-45f3-b76c-c924f42c6f3f)

1. I designed it with 3 different buttons for left, right and jump for now, but one joystick for left and right and another jump button could also make sense, to reduce the number of fingers required to play (which would be limited by hardware for every user).
2. I'm not sure about a virtual joystick for fire/hooking. I currently designed it so you fire/hook exactly where you touch on the screen, since that seems like the most intuitive way for touch input. The "Fire/Hook" button toggles what the touch does. While one of them is already held down, you can use another finger to use the other action after toggling. I'll also try heinrich5991's idea "The second touch while hooking could shoot." Using both actions exactly at the same time is currently not possible.
3. This might be a general issue with SDL or Android. I have a similar issue, where pressing down 3 or more fingers at the same time will cause all of the fingers to be released immediately, whereas multi-touch works correctly even with 5 and more fingers if I press them individually. If I use the Android pointer location debug tool it works correctly though, which makes me believe it's an SDL issue. Maybe it incorrectly gets detected as a gesture instead. Still needs more testing.
4. See #8503.
5. If this completely breaks phones, maybe we could limit the maximum zoom. Also affects the editor though.
6. Yes, that's what the hamburger menu is for. It toggles visibility of buttons for local/remote console, all/team chat and scoreboard currently. Pausing could probably also get a button. Emoticons and spectator UI would also get buttons but they are currently secondary, since more changes are required so they also work with touch input even if you could open them. Zoom controls probably need buttons as well, since pinching gestures might be triggered accidentally ingame.

**Comment by Jupeyy** [comment] 2024-06-20 09:23
ForgottenCat also said that chinese characters crash the client:
"Oh, I forget another issue.
When  I try to send chinese characters in chat, the client will crush.
Including full-width characters, such as "？"
？=crush, ?=ok"

I assume that will simply work too, but yeah should be tested.


About 5. we already have a zoom limit in newer clients, I assume that limit should be enough even on phones, I guess DDNet 9 simply had no limit at all :D

**Comment by Robyt3** [comment] 2024-06-23 15:56
> 3. I have a similar issue, where pressing down 3 or more fingers at the same time will cause all of the fingers to be released immediately, whereas multi-touch works correctly even with 5 and more fingers if I press them individually. If I use the Android pointer location debug tool it works correctly though, which makes me believe it's an SDL issue. Maybe it incorrectly gets detected as a gesture instead. Still needs more testing.

It seems this is related to a feature where you can hold and swipe 3 fingers to take a screenshot. The adb log showed that the event was being ignored because of the enabled screenshot gesture. It can be fixed by disabling the screenshot gesture feature in the device settings.

**Comment by K1nop10** [comment] 2024-07-29 12:05
I think sliding on buttons is a great idea. Maybe it can be applied to more buttons. If slide left can be switching to previous weapon, then for other buttons sliding can be more different bindings.
But when after sliding if your finger lands on another button, it will be triggered as well. That's a problem.

**Comment by K1nop10** [comment] 2024-07-29 12:14
![IMG_20240729_201226](https://github.com/user-attachments/assets/3c51458c-696e-409c-8df2-424a61543214)
If you tap these 3 places at almost the same time, all will be released. The old client also has this bug.

**Comment by Robyt3** [comment] 2024-07-29 15:59
> If you tap these 3 places at almost the same time, all will be released. The old client also has this bug.

This is very likely related to bugs in features of your operating system. You should be able to observe this behavior in any app. The only way to prevent this is to disable any 3-finger gestures in the device settings (https://github.com/ddnet/ddnet/issues/8359#issuecomment-2185092793)

**Comment by K1nop10** [comment] 2024-07-30 02:37
> > If you tap these 3 places at almost the same time, all will be released. The old client also has this bug.
> 
> This is very likely related to bugs in features of your operating system. You should be able to observe this behavior in any app. The only way to prevent this is to disable any 3-finger gestures in the device settings ([#8359 (comment)](https://github.com/ddnet/ddnet/issues/8359#issuecomment-2185092793))

My mistake. MIUI designers have done nothing useful. Sorry for the trouble.

**Closed** 2024-12-01 12:43 UTC
Labels: enhancement, android, needs-discussion
