### ISSUE TITLE
[Assertion Error] Demo recorder alreay recording

### ISSUE THREAD

**Issue by CAESIUS-TIM** [ddnet/ddnet#7802] opened 2024-01-14 12:17 UTC
![image](https://github.com/ddnet/ddnet/assets/60285058/da7b1331-1972-4247-85e0-5218ec2941a3)

**Comment by jxsl13** [comment] 2024-01-14 13:01
that one I also had in chiller's ddnet-insta mod

**Comment by Robyt3** [comment] 2024-01-14 18:37
Should both be fixed by #7571 already with latest nightly, assuming both were caused by using the `record` command.

**Comment by jxsl13** [comment] 2024-01-14 18:54
I did enable my demos using the config file, so that demos should be recorder all the time.

**Comment by Robyt3** [comment] 2024-01-22 23:04
Should be fixed in nightly by #7571 and #7837.

**Closed by Robyt3** 2024-01-22 23:03 UTC
