### ISSUE TITLE
"Name" string can't be translated correctly

### ISSUE THREAD

**Issue by EGYT5453** [ddnet/ddnet#8679] opened 2024-08-04 11:46 UTC
In Ukrainian and other Slavic languages, we have two words for "name", "ім'я" for personal names and "назва" for proper nouns (for example, Andrew is "ім'я", and DDNet is "назва"). Because server browser uses the same string as everything else, it is impossible to translate the string "Name" to these languages correctly.

**Comment by MilkeeyCat** [comment] 2024-08-04 11:48
#8434?

**Comment by Robyt3** [comment] 2024-08-04 11:48
Duplicate of #8434.

**Closed by Robyt3** 2024-08-04 11:48 UTC

**Comment by EGYT5453** [comment] 2024-08-04 11:50
Whoops, forgot about that one
