### ISSUE TITLE
Add DDraceNetwork to Consoles Store

### ISSUE THREAD

**Issue by Itube17** [ddnet/ddnet#5425] opened 2022-06-15 12:35 UTC
I saw already an pic where someone play teeworlds with controller. I would also help to make it playable.

**Comment by heinrich5991** [comment] 2022-06-15 12:48
What is consoles store?

**Comment by Chairn** [comment] 2022-06-15 16:12
I guess he speaks about play store and apple store? Maybe other stores? 

Sounds like duplicate of https://github.com/ddnet/ddnet/issues/4644

/remind me 1 week

**Comment by Chairn** [comment] 2022-06-24 04:45
closed as duplicate of #4644

**Closed by Chairn** 2022-06-24 04:45 UTC
Labels: reminder
