### ISSUE TITLE
Don't warn about unfinishable map for super team

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4205] opened 2021-10-09 12:09 UTC
CC #4162

![](https://cdn.discordapp.com/attachments/757720336274948198/896157148319465506/unknown.png)

**Comment by Chairn** [comment] 2022-10-18 19:31
Can confirm the problem is still there :)

**Comment by Robyt3** [comment] 2024-02-04 17:20
Fixed by #7814.

**Closed by Robyt3** 2024-02-04 17:20 UTC
Labels: bug, server
