### ISSUE TITLE
dynamically updated maps (discussion)

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#8397] opened 2024-05-26 09:57 UTC
Is there a possibility of dynamic maps (i.e. maps that can update tiles while tees are playing the map)? I'm not sure exactly how this would work, but I imagine that instead of storing the entire map client-side, the server can simply send the map resources for the client to store and separately send tile data when the tee first loads in as well as whenever the map updates its tiles.

Some cool use-cases:

- Better switch tile mechanics (switchability to any tile)
- Possible future in-game map editing on the fly
- Better modularity for map shape in the future (a system like sending resources and tiles separately we could make changes to the structure of a DDNet map in the future such as moving tiles more easily)

Would obviously be a pretty big change, but I'd like to open this possibility to discussion.

**Comment by heinrich5991** [comment] 2024-05-26 10:00
I agree that this would be cool.

When the time comes to design such a feature from a technical perspective, demos will also need a solution.

**Comment by ChillerDragon** [comment] 2024-05-26 11:18
Duplicate of https://github.com/ddnet/ddnet/issues/7666?

**Comment by ChillerDragon** [comment] 2024-05-26 11:19
And https://github.com/ddnet/ddnet/issues/7296

**Comment by l-ouis** [comment] 2024-05-26 11:41
Also somewhat related to #5165

But maybe this discussion is a bit more broad than these three. I guess devs can close this if they see fit.

In terms of demos, what about the demo file containing:

1. initial map data sent to the tee (assets and initial tile + asset locations on map)
2. A list of tick timestamps for each tile netmessage change

**Comment by heinrich5991** [comment] 2024-05-26 11:58
Duplicate of #7666. Please discuss the proposal over there. (You can post your initial post there if you want.)

**Closed by heinrich5991** 2024-05-26 11:58 UTC
