### ISSUE TITLE
Map loads twice (probably HTTP map downloading broken)

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#1250] opened 2018-08-12 14:45 UTC
since 11.2.1 every(almost) map loads twice.
When I connecting to the server (while I dont have server map locally) map loading appears and when progress bar reach 100% it become 0% and going to 100% once again. It is possible to connect to the server only if progress bar reach 100% twice in a single try

It is looks like pure bug (for user at least)
Disabling "Try fast HTTP map download first" fixes the problem but maps loading is pretty slow then

**Comment by def-** [comment] 2018-08-12 14:53
Do you have logs? Can't reproduce locally with either Linux build or win64 build in Wine.

**Comment by BannZay** [comment] 2018-08-12 16:27
here is connecting to the ddnet server log

```
[2018-08-12 19:15:05][client]: connecting to '95.172.92.151:8003'
[2018-08-12 19:15:05][host lookup]: host='95.172.92.151' port=8003 3
[2018-08-12 19:15:05][client]: timeout code '5deEqD7NLqVmFmZC' (normal)
[2018-08-12 19:15:05][client]: timeout code 'kg6MGfqLXfK5oUmb' (dummy)
[2018-08-12 19:15:05][client]: connected, sending info
[2018-08-12 19:15:05][client]: offline error='Wrong password'
[2018-08-12 19:15:10][client]: connecting to '95.172.92.151:8316'
[2018-08-12 19:15:10][host lookup]: host='95.172.92.151' port=8316 3
[2018-08-12 19:15:10][client]: timeout code '64aoh74PmnFf7aAa' (normal)
[2018-08-12 19:15:10][client]: timeout code 'h37bSA4AhpnhRCHF' (dummy)
[2018-08-12 19:15:10][client]: connected, sending info
[2018-08-12 19:15:10][client]: loading map, map=HellGate X wantedsha256=5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e  crc=b8ccfe07
[2018-08-12 19:15:10][datafile]: loading. filename='maps/HellGate X.map'
[2018-08-12 19:15:10][datafile]: could not open 'maps/HellGate X.map'
[2018-08-12 19:15:10][datafile]: loading. filename='downloadedmaps/HellGate X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map'
[2018-08-12 19:15:10][datafile]: could not open 'downloadedmaps/HellGate X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map'
[2018-08-12 19:15:10][datafile]: loading. filename='downloadedmaps/HellGate X_b8ccfe07.map'
[2018-08-12 19:15:10][datafile]: could not open 'downloadedmaps/HellGate X_b8ccfe07.map'
[2018-08-12 19:15:10][client/network]: starting to download map to 'downloadedmaps/HellGate X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map.tmp'
[2018-08-12 19:15:10][http]: http https://maps.ddnet.tw/HellGate%20X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map
[2018-08-12 19:15:11][http]: task done https://maps.ddnet.tw/HellGate%20X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map
[2018-08-12 19:15:11][client/network]: download complete, loading map
[2018-08-12 19:15:11][datafile]: loading. filename='downloadedmaps/HellGate X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map'
[2018-08-12 19:15:11][datafile]: could not open 'downloadedmaps/HellGate X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map'
[2018-08-12 19:15:13][client/network]: download complete, loading map
[2018-08-12 19:15:13][datafile]: loading. filename='downloadedmaps/HellGate X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map'
[2018-08-12 19:15:13][datafile]: allocsize=2744
[2018-08-12 19:15:13][datafile]: readsize=2376
[2018-08-12 19:15:13][datafile]: swaplen=2396
[2018-08-12 19:15:13][datafile]: item_size=1980
[2018-08-12 19:15:13][datafile]: loading done. datafile='downloadedmaps/HellGate X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map'
[2018-08-12 19:15:13][client]: loaded map 'downloadedmaps/HellGate X_b8ccfe07_5b5b4560d5df571cb32bb3679384869af4afe4d78cd94974ed6b4c25f6f0b65e.map'
[2018-08-12 19:15:13][client/network]: loading done
[2018-08-12 19:15:13][motd]: DDraceNetwork - ddnet.tw
[2018-08-12 19:15:13][motd]:           ??.Moderate Server
[2018-08-12 19:15:13][motd]:
[2018-08-12 19:15:13][motd]: ?-?"?           C?????????╪????> M??????
[2018-08-12 19:15:13][motd]: ?", Map: HellGate X
[2018-08-12 19:15:13][motd]: ?", Mapper: Hitomi
[2018-08-12 19:15:13][motd]: ?", Difficulty: ??.??.??.??.??° (13 Points)
[2018-08-12 19:15:13][motd]: ?", Released on 2014-07-29
[2018-08-12 19:15:13][motd]: ?", 351 finishes by 331 tees
[2018-08-12 19:15:13][motd]: ?", Top Time: 18:47
[2018-08-12 19:15:13][motd]: ?", Average Time: 66:48
[2018-08-12 19:15:13][motd]: ?", Worst Time: 190:18
[2018-08-12 19:15:13][motd]: ?°?"??"??"??"??"??"??"??"??"??"??"??"??"??"??"??"??"??"??"??"??"??"??"?
[2018-08-12 19:15:13][datafile]: loading data index=11 size=12329 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=17 size=1160 uncompressed=360000
[2018-08-12 19:15:13][datafile]: loading data index=15 size=1259 uncompressed=1080000
[2018-08-12 19:15:13][datafile]: loading data index=13 size=2626 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=9 size=726 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=10 size=429 uncompressed=420000
[2018-08-12 19:15:13][datafile]: loading data index=12 size=721 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=14 size=721 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=16 size=721 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=18 size=949 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=19 size=10635 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=20 size=2016 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=21 size=1904 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=22 size=814 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=23 size=10371 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=24 size=5003 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=25 size=1243 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=26 size=721 uncompressed=720000
[2018-08-12 19:15:13][datafile]: loading data index=1 size=33448 uncompressed=4194304
[2018-08-12 19:15:13][datafile]: loading data index=3 size=13774 uncompressed=4194304
[2018-08-12 19:15:13][datafile]: loading data index=5 size=237373 uncompressed=4194304
[2018-08-12 19:15:13][datafile]: loading data index=7 size=10180 uncompressed=4194304
[2018-08-12 19:15:13][datafile]: loading data index=8 size=20 uncompressed=12
[2018-08-12 19:15:13][chat]: *** 'BannZay' entered and joined the game
[2018-08-12 19:15:13][chat]: *** DDraceNetwork Mod. Version: 0.6.4, 11.3.1
[2018-08-12 19:15:13][chat]: *** please visit DDNet.tw or say /info for more info
[2018-08-12 19:15:13][chat]: *** Welcome to DDraceNetwork!
[2018-08-12 19:15:14][demo_recorder]: Recording to 'demos/auto/race/HellGate X_tmp_10296.demo'
```
I`m using Win10 x64 
Its not rare problem for windows users

**Comment by def-** [comment] 2018-08-12 16:35
I'd guess it's caused by https://github.com/ddnet/ddnet/pull/1136 . Mind taking a look @heinrich5991 ?

**Comment by heinrich5991** [comment] 2018-08-13 16:00
Sounds like I caused this. Will look into it.

**Comment by heinrich5991** [comment] 2018-08-29 18:59
Argh. Haven't looked into it yet. :/ We really need a developer who's usually working on Windows…

**Comment by def-** [comment] 2018-09-06 17:10
Might this also be related to people not getting info.json updated anymore?

**Comment by Learath2** [comment] 2018-09-20 01:14
Hmm, I couldn't really get it to happen on my Windows 7 64bit either. I'll try a couple other computers :/

**Comment by Learath2** [comment] 2018-09-20 15:56
Oh, could it be curl reporting progress wrong? Which would fool our code to think "download complete".

**Comment by Learath2** [comment] 2018-09-20 16:59
If anyone can reliably reproduce this on their computer give [this](https://ci.appveyor.com/api/buildjobs/mvtjgro4ay08r8d3/artifacts/build64%2FDDNet-11.4.3-win64.zip) a try. It should tell us why the file doesn't open.

**Comment by msiglreith** [comment] 2018-09-21 13:46
Played a bit around with it yesterday. The issues seems to be file access restrictions when trying to rename the file with MoveFileEx (returning 0x20). The involved deletion step seems not to be allowed.

**Comment by heinrich5991** [comment] 2018-09-21 13:57
Can you check the result of `GetLastError()` if the move fails? It should contain a more detailed error.

**Comment by msiglreith** [comment] 2018-09-21 14:02
@heinrich5991 `0x20` as mentioned above (process can't access the file, because it used by another process..)

**Comment by trikiman** [comment] 2018-10-01 22:15
`[2018-10-02 01:14:16][client]: starting...
[2018-10-02 01:14:16][gfx]: Using OpenGL version 3.3.
[2018-10-02 01:14:16][client/sound]: sound init successful
[2018-10-02 01:14:16][textrender]: loaded pFont from 'data/fonts/Icons.ttf'
[2018-10-02 01:14:16][engine/mastersrv]: refreshing master server addresses
[2018-10-02 01:14:16][host lookup]: host='master1.teeworlds.com' port=0 3
[2018-10-02 01:14:16][host lookup]: host='master2.teeworlds.com' port=0 3
[2018-10-02 01:14:16][host lookup]: host='master3.teeworlds.com' port=0 3
[2018-10-02 01:14:16][localization]: loaded 'languages/russian.txt'
[2018-10-02 01:14:16][textrender]: loaded pFont from 'data/fonts/DejaVuSansCJKName.ttf'
[2018-10-02 01:14:16][textrender]: default pFont set 0000000002D79880
[2018-10-02 01:14:16][datafile]: loading. filename='maps/.map'
[2018-10-02 01:14:16][datafile]: could not open 'maps/.map'
[2018-10-02 01:14:16][host lookup]: host='master4.teeworlds.com' port=0 3
[2018-10-02 01:14:17][gameclient]: initialisation finished after 793,47ms
[2018-10-02 01:14:17][client]: version 0.6 626fce9a778df4d4
[2018-10-02 01:14:17][http]: http https://info.ddnet.tw/info?name=triki
[2018-10-02 01:14:17][engine/mastersrv]: saving addresses
[2018-10-02 01:14:18][http]: task done https://info.ddnet.tw/info?name=triki
[2018-10-02 01:14:18][storage]: failed to rename: C:\Users\triki\AppData\Roaming/Teeworlds/ddnet-info.json.tmp -> C:\Users\triki\AppData\Roaming/Teeworlds/ddnet-info.json
[2018-10-02 01:14:20][client]: connecting to '95.172.92.151:8322'
[2018-10-02 01:14:20][host lookup]: host='95.172.92.151' port=8322 3
[2018-10-02 01:14:20][client]: timeout code 'DYSVam5agpZ6pYUh' (normal)
[2018-10-02 01:14:20][client]: timeout code 'aVatnGNotqX9WXD6' (dummy)
[2018-10-02 01:14:20][client]: connected, sending info
[2018-10-02 01:14:20][client]: loading map, map=Greed wanted sha256=d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a crc=a6683624
[2018-10-02 01:14:20][datafile]: loading. filename='maps/Greed.map'
[2018-10-02 01:14:20][datafile]: could not open 'maps/Greed.map'
[2018-10-02 01:14:20][datafile]: loading. filename='downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map'
[2018-10-02 01:14:20][datafile]: could not open 'downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map'
[2018-10-02 01:14:20][datafile]: loading. filename='downloadedmaps/Greed_a6683624.map'
[2018-10-02 01:14:20][datafile]: could not open 'downloadedmaps/Greed_a6683624.map'
[2018-10-02 01:14:20][client/network]: starting to download map to 'downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map.tmp'
[2018-10-02 01:14:20][http]: http https://maps.ddnet.tw/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map
[2018-10-02 01:14:21][http]: task done https://maps.ddnet.tw/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map
[2018-10-02 01:14:21][client/network]: download complete, loading map
[2018-10-02 01:14:21][storage]: failed to rename: C:\Users\triki\AppData\Roaming/Teeworlds/downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map.tmp -> C:\Users\triki\AppData\Roaming/Teeworlds/downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map
[2018-10-02 01:14:21][datafile]: loading. filename='downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map'
[2018-10-02 01:14:21][datafile]: could not open 'downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map'
[2018-10-02 01:14:51][client/network]: download complete, loading map
[2018-10-02 01:14:51][datafile]: loading. filename='downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map'
[2018-10-02 01:14:51][datafile]: allocsize=3228
[2018-10-02 01:14:51][datafile]: readsize=2796
[2018-10-02 01:14:51][datafile]: swaplen=2816
[2018-10-02 01:14:51][datafile]: item_size=2296
[2018-10-02 01:14:51][datafile]: loading done. datafile='downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map'
[2018-10-02 01:14:51][client]: loaded map 'downloadedmaps/Greed_a6683624_d8b8e5c243bfb3f88ea66430a1f36cd340f691ab85754cbd0998268c7cd1215a.map'
[2018-10-02 01:14:51][client/network]: loading done
[2018-10-02 01:14:51][motd]: DDraceNetwork - ddnet.tw
[2018-10-02 01:14:51][motd]:               в??в??Dummy Server
[2018-10-02 01:14:51][motd]:
[2018-10-02 01:14:51][motd]: в-в"?           Cб??К?К?б?╪Й?б?> Mб??б??
[2018-10-02 01:14:51][motd]: в"' Map: Greed
[2018-10-02 01:14:51][motd]: в"' Mapper: Kosho
[2018-10-02 01:14:51][motd]: в"' Difficulty: в?:в?:в?°в?°в?° (15 Points)
[2018-10-02 01:14:51][motd]: в"' Released on 2016-06-24
[2018-10-02 01:14:51][motd]: в"' 1645 finishes by 1261 tees
[2018-10-02 01:14:51][motd]: в"' Top Time: 08:26
[2018-10-02 01:14:51][motd]: в"' Average Time: 33:02
[2018-10-02 01:14:51][motd]: в"' Worst Time: 300:43
[2018-10-02 01:14:51][motd]: в°в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?в"?
[2018-10-02 01:14:51][datafile]: loading data index=18 size=5202 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=26 size=869 uncompressed=191250
[2018-10-02 01:14:51][datafile]: loading data index=28 size=766 uncompressed=573750
[2018-10-02 01:14:51][datafile]: loading data index=24 size=533 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=22 size=328 uncompressed=191250
[2018-10-02 01:14:51][datafile]: loading data index=20 size=850 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=19 size=394 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=21 size=394 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=23 size=394 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=25 size=394 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=27 size=394 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=29 size=4388 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=30 size=3224 uncompressed=380800
[2018-10-02 01:14:51][datafile]: loading data index=31 size=692 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=32 size=781 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=33 size=706 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=34 size=524 uncompressed=382500
[2018-10-02 01:14:51][datafile]: loading data index=2 size=243134 uncompressed=4194304
[2018-10-02 01:14:51][datafile]: loading data index=4 size=31295 uncompressed=4194304
[2018-10-02 01:14:51][datafile]: loading data index=6 size=62983 uncompressed=4194304
[2018-10-02 01:14:51][datafile]: loading data index=8 size=190152 uncompressed=4194304
[2018-10-02 01:14:51][datafile]: loading data index=10 size=41547 uncompressed=1024000
[2018-10-02 01:14:51][datafile]: loading data index=11 size=18 uncompressed=10
[2018-10-02 01:14:51][datafile]: loading data index=12 size=12 uncompressed=4
[2018-10-02 01:14:51][datafile]: loading data index=13 size=98 uncompressed=152
[2018-10-02 01:14:51][datafile]: loading data index=14 size=627 uncompressed=2432
[2018-10-02 01:14:51][datafile]: loading data index=15 size=77 uncompressed=152
[2018-10-02 01:14:51][datafile]: loading data index=16 size=96 uncompressed=152
[2018-10-02 01:14:51][datafile]: loading data index=17 size=55 uncompressed=152
[2018-10-02 01:14:52][chat]: *** 'triki' entered and joined the game
[2018-10-02 01:14:52][chat]: *** DDraceNetwork Mod. Version: 0.6.4, 11.4.3
[2018-10-02 01:14:52][chat]: *** please visit DDNet.tw or say /info for more info
[2018-10-02 01:14:52][chat]: *** Welcome to DDraceNetwork!
[2018-10-02 01:14:52][chat]: *** Please join a team before you start
[2018-10-02 01:14:52][demo_recorder]: Recording to 'demos/auto/race/Greed_tmp_10592.demo'
[2018-10-02 01:15:12][demo_recorder]: Stopped recording
[2018-10-02 01:15:12][storage]: failed to remove: C:\Users\triki\AppData\Roaming/Teeworlds/demos/auto/race/Greed_tmp_10592.demo
`

**Comment by def-** [comment] 2018-10-02 06:01
```
[2018-10-02 01:14:18][storage]: failed to rename: C:\Users\triki\AppData\Roaming/Teeworlds/ddnet-info.json.tmp -> C:\Users\triki\AppData\Roaming/Teeworlds/ddnet-info.json
```

**Comment by Learath2** [comment] 2018-10-04 14:02
@cinaera said he could reproduce this on his computer. I guess he is our only chance because I couldn't get this to happen no matter what I tried.

**Comment by def-** [comment] 2018-10-04 14:05
If on Windows it's a problem to move a file other an existing file that is opened already, can we remove the opened file first or would that cause the same problem?

**Comment by heinrich5991** [comment] 2018-10-04 14:08
I think removing will have the same problems as moving a different file to the same location.

I also thought that I'm correctly closing the file before replacing it, but that's apparently not the case. My model of the Windows file system isn't that good anyway…

**Comment by def-** [comment] 2018-10-04 14:12
Then let's at least check what io_close returns I guess.

**Comment by fokkonaut** [comment] 2018-10-11 21:59
close

**Comment by Learath2** [comment] 2018-10-13 12:34
@trikiman && @msiglreith && @BannZay: Can you verify that this was fixed by #1327 so we can close it?

**Comment by trikiman** [comment] 2018-10-20 14:12
> @trikiman && @msiglreith && @BannZay: Can you verify that this was fixed by #1327 so we can close it?
 i need smth update? If no i still have this problem.

**Comment by Learath2** [comment] 2018-10-20 14:42
[This](https://ci.appveyor.com/api/buildjobs/rpc2c5rtdqckq9ua/artifacts/build64%2FDDNet-11.4.4-win64.zip) is the build for that commit. We didn't release a version with it yet.

**Comment by trikiman** [comment] 2018-11-21 19:08
no have problem anymore.

**Closed** 2018-11-21 19:15 UTC
Labels: bug, client
