### ISSUE TITLE
Switching freeze stars and slider

### ISSUE THREAD

**Issue by NikProgramer** [ddnet/ddnet#7329] opened 2023-10-09 09:20 UTC
Why not add a switch that will return 3 stars instead of a new frieze strip? I think many old ddnet players will enjoy playing with stars and the ninja effect after hitting and entering freeze.

**Comment by def-** [comment] 2023-10-09 09:26
We don't want more options like this.

**Comment by Robyt3** [comment] 2023-10-10 17:37
Duplicate of #6028.

**Closed by Robyt3** 2023-10-10 17:37 UTC
